#!/usr/bin/env bash

set -Eeuo pipefail

[[ -x "$(command -v yamllint)" ]] || exit 0

ecode='0'
while read -r path; do
	if [[ ! -d "$path" && "$path" =~ \.ya?ml$ ]]; then
		if ! yamllint -s "$path"; then
			ecode='1'
		fi
	fi
done < <(git diff --cached --name-only --diff-filter=CARM)

[[ "$ecode" == '0' ]] || echo '^^^ issues found in yaml files ^^^'

exit "$ecode"
