#!/usr/bin/env bash

set -Euo pipefail

{
	if command git rev-parse HEAD &>/dev/null; then
		git ls-files -c --exclude-standard --recurse-submodules
		git ls-files -o --exclude-standard
	else
		_fzf_compgen_helper . 'f'
	fi
} | grep -vP '\A(?:webservice|slib)/' 2>/dev/null
