# vim: syntax=zsh foldmethod=marker

source-file "$XDG_CONFIG_HOME/shell/rc"
source-file "$XDG_CONFIG_HOME/shell/rc.work"

# => Install antigen --------------------------------------------------------------------------------------------- {{{1

function install-antigen() {
	source       "$ZDOTDIR/antigen.zsh"
	antigen init "$ZDOTDIR/antigenrc.zsh"
}

if [[ ! -d ${ADOTDIR} ]]; then
	echo -n "Proceed with installing antigen and plugins (y/n/p)? "
	read choice
	case "$choice" in
		y|Y )
			umask 022
			install-antigen
			;;
		p|P )
			enable-proxy
			umask 022
			install-antigen
			;;
		* )
			;;
	esac
else
	install-antigen
fi

[[ -n "$GOPATH"                ]] && _appendvar_head PATH "$GOPATH/bin"
[[ -n "$GEM_HOME"              ]] && _appendvar_head PATH "$GEM_HOME/bin"
[[ -n "$PERLBREW_PATH"         ]] && _appendvar_head PATH "$PERLBREW_PATH"
[[ -d "$HOME/.local/bin"       ]] && _appendvar_head PATH "$HOME/.local/bin"
[[ -d "$HOME/.local/scripts"   ]] && _appendvar_head PATH "$HOME/.local/scripts"
[[ -d "$HOME/.cache/bin"       ]] && _appendvar_head PATH "$HOME/.cache/bin"
export PATH

# => broot ------------------------------------------------------------------------------------------------------- {{{1

# This script was automatically generated by the broot program
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br {
	f=$(mktemp)
	(
		set +e
		broot --outcmd "$f" --hidden -dp "$@"
		code=$?
		if [ "$code" != 0 ]; then
			rm -f "$f"
			exit "$code"
		fi
	)
	code=$?
	if [ "$code" != 0 ]; then
		return "$code"
	fi
	d=$(<"$f")
	rm -f "$f"
	eval "$d"
}

# => show profiler ----------------------------------------------------------------------------------------------- {{{1

#zprof
