---
# https://prettier.io/docs/en/options
# https://json.schemastore.org/prettierrc
arrowParens: avoid
bracketSameLine: false
bracketSpacing: false
htmlWhitespaceSensitivity: ignore
jsxSingleQuote: true

overrides:
  - files: ['*.html', '*.html.ep']
    options:
      parser: html

proseWrap: preserve
quoteProps: consistent
semi: true
singleAttributePerLine: true
singleQuote: true
trailingComma: all
vueIndentScriptAndStyle: true
