requires "Cpanel::JSON::XS";
requires "Future::AsyncAwait";
requires "IO::Socket::SSL";
requires "IO::Socket::Socks";
requires "Mojolicious";
requires "Net::DNS::Native";
requires "Role::Tiny";

requires "App::cpanminus";
requires "Carp::Always";
requires "Carp::Assert";
requires "Carp::Assert::More";
requires "Data::Dump";
requires "Data::Printer";
requires "DateTime::TimeZone";
requires "File::Map";
requires "HTML::Tagset";
requires "IO::Async";
requires "Log::Any";
requires "Path::Tiny";
requires "Regexp::Debugger";
requires "String::ShellQuote";
requires "Syntax::Keyword::Match";
requires "Syntax::Operator::Eqr";
requires "Syntax::Operator::Equ";
requires "Syntax::Operator::In";
requires "Syntax::Operator::Is";
requires "Text::CSV";
requires "Time::Moment";
# requires "YAML::XS"; # my repo has fixes for sequence indentation

on 'develop' => sub {
    requires "Devel::Trace";
    requires "MetaCPAN::Client";
    requires "Perl::Critic";
    requires "Perl::Critic::Pulp";
};

feature 'develop' => sub {
#    requires "App::perlimports"; dep-hell
    requires "Code::TidyAll";
    requires "Parallel::ForkManager"; # for Code::TidyAll
    requires "Sub::StrictDecl";
    requires "Test2::Harness";
};

feature 'system' => sub {
    requires "Chipcard::PCSC::Card"; # for pcsc_scan, may fail
    requires "Neovim::Ext";
};

feature 'mojo-extras' => sub {
    requires "EV";
    requires "Mojo::Run3";
    requires "Mojo::SQLite";
    # requires "IO::Async::Loop::Mojo";
    # requires "Mojo::Reactor::IOAsync";
};

feature 'mojo-openapi' => sub {
    requires "Crypt::JWT";
    requires "CryptX";
    requires "Mojo::Pg";
    requires "Mojolicious::Plugin::OpenAPI";
    requires "Mojolicious::Plugin::Status";
    requires "Mojolicious::Plugin::SwaggerUI";
};

feature 'sqlite' => sub {
    requires "DBD::SQLite";
    requires "Mojo::SQLite";
};

feature 'misc' => sub {
    requires "CHI";
    requires "DateTime";
    requires "Sereal";
    requires "Sort::Naturally";
};

feature 'experiment' => sub {
    requires "List::UtilsBy";
    requires "Object::Pad::FieldAttr::Checked";
    requires "Object::Pad::FieldAttr::Isa";
    requires "Signature::Attribute::Checked";
    requires "Sublike::Extended";
    requires "Syntax::Operator::Zip";
    requires "assign";
};

feature 'image' => sub {
    requires "Image::ExifTool";
    requires "Image::Hash";
};

feature 'repl' => sub {
#    requires "DBI::Shell"; dep-hell
#    requires "Devel::IPerl"; dep-hell
    requires "Reply";
    requires "Term::ReadKey";
    requires "Term::ReadLine::Gnu";
};
