alias               cpv='rsync -Pa'
alias        rsync-copy='rsync -ha  --info=progress2'
alias        rsync-move='rsync -ha  --info=progress2 --remove-source-files'
alias      rsync-update='rsync -hau --info=progress2'
alias rsync-synchronize='rsync -hau --info=progress2 --delete'
