# Use GPU-accelerated video output by default
vo=gpu
hwdec=auto

alang=en,nl,ru
slang=en,nl,ru
vlang=en,nl,ru
audio-fallback-to-null=yes
audio-file-auto=fuzzy
cursor-autohide-fs-only
load-scripts=yes
osd-duration=5000
save-position-on-quit
sub-auto=fuzzy
volume=50
watch-later-directory=~/.cache/mpv

osd-bar-align-y=1
osd-bar-h=1
osd-bar-w=90

# set desired video format for watching youtube video with youtube-dl
ytdl-format=bestvideo[ext=mp4,height<=480]+bestaudio[ext=m4a]/best[ext=mp4]/best
