# man: mpv

input-ipc-server=/tmp/mpvsocket

# Use GPU-accelerated video output by default
vo=gpu
hwdec=auto

alang=en,nl,ru
slang=en,nl,ru
vlang=en,nl,ru
audio-fallback-to-null=yes
audio-file-auto=fuzzy
cursor-autohide-fs-only
load-scripts=yes
osd-duration=5000
save-position-on-quit
sub-auto=fuzzy
volume=50
watch-later-directory=~/.cache/mpv
ontop=yes
on-all-workspaces
geometry=25%-+20-+30

osd-bar-align-y=1
osd-bar-h=1
osd-bar-w=90

# set desired video format for watching youtube video with youtube-dl
#ytdl-format=bestvideo[ext=mp4,height<=720]+bestaudio[ext=m4a]/best[ext=mp4]/best
# youtube-dl --external-downloader=aria2c --external-downloader-args '--min-split-size=1M --max-connection-per-server=16 --max-concurrent-downloads=16 --split=16' $URL

# yt-dlp support
ytdl-raw-options=format-sort="codec:h264,+res:720"
