# Use GPU-accelerated video output by default.
vo=gpu
hwdec=auto
# Use quotes for text that can contain spaces:
#status-msg="Time: ${time-pos}"
alang=en,nl,ru
slang=en,nl,ru
vlang=en,nl,ru
save-position-on-quit
audio-fallback-to-null=yes
audio-file-auto=fuzzy
sub-auto=fuzzy
osd-duration=5000
watch-later-directory=~/.cache/mpv
save-position-on-quit
volume=50
load-scripts=yes

cursor-autohide-fs-only

osd-bar-align-y=1
osd-bar-h=1
osd-bar-w=90

ytdl-format=bestvideo[ext=mp4,height<=480]+bestaudio[ext=m4a]/best[ext=mp4]/best
