requires "App::cpanminus";

# Mojolicious
requires "Future::AsyncAwait";
requires "IO::Socket::SSL";
requires "Mojolicious";
requires "Role::Tiny";

requires "File::Map";
requires "Log::Any";
requires "Path::Tiny";
requires "Regexp::Debugger";
requires "Syntax::Keyword::Match";
requires "Syntax::Operator::Equ";
requires "Time::Moment";
requires "YAML::XS";

on 'develop' => sub {
    requires "App::perlimports";
    requires "Carp::Always";
    requires "Code::TidyAll";
    requires "Data::Dump";
    requires "Data::Printer";
    requires "Parallel::ForkManager"; # for Code::TidyAll
    requires "Perl::Critic";
    requires "Perl::Critic::Pulp";
    requires "Sub::StrictDecl";
    requires "Test2::Harness";
    requires "Test2::Suite";
};

feature 'mojo-extras' => sub {
    requires "Cpanel::JSON::XS";
    requires "EV";
    requires "IO::Socket::Socks";
    requires "Net::DNS::Native";

    requires "Mojo::Run3";
};

feature 'misc' => sub {
    requires "CHI";
    requires "DateTime";
    requires "DateTime::TimeZone";
    requires "Neovim::Ext";
    requires "Sereal";
    requires "Sort::Naturally";
};

feature 'experiment' => sub {
    requires "List::UtilsBy";
    requires "assign";
};

feature 'image' => sub {
    requires "Image::ExifTool";
    requires "Image::Hash";
};

feature 'openapi' => sub {
    requires "Crypt::JWT";
    requires "CryptX";
    requires "Mojo::Pg";
    requires "Mojolicious::Plugin::OpenAPI";
    requires "Mojolicious::Plugin::Status";
    requires "Mojolicious::Plugin::SwaggerUI";
};

feature 'repl' => sub {
    requires "Devel::IPerl";
    requires "Reply";
    requires "Term::ReadKey";
    requires "Term::ReadLine::Gnu";
};
