#!/usr/bin/env bash

set -Eeuo pipefail

ROLE=$1
shift

git-in-repo || {
	echo 'Please run in git repo'
	exit 1
}

cd "$(git root)" &>/dev/null

ROLE="$(realpath --relative-to="$PWD/roles" "$ROLE")"

echo "Trying to apply role '$ROLE'"

export ANSIBLE_FORCE_COLOR='True'
export ANSIBLE_RETRY_FILES_ENABLED='False'
ANSIBLE_ROLES_PATH="$PWD/roles:${ANSIBLE_ROLES_PATH:-}"
export ANSIBLE_ROLES_PATH

TMPFILE=$(mktemp -u)
cat > "$TMPFILE" <<END
---
- hosts: [all]
  roles:
    - $ROLE
END

echo "executing: ansible-playbook $ROLE $*"
ansible-playbook "$TMPFILE" "$@"
