#!/usr/bin/env bash

set -Eeuo pipefail

tmpdir="$(mktemp --tmpdir="${XDG_RUNTIME_DIR:-/tmp}" -d --suffix 'build-git-credential-libsecret')"
trap 'rm -rf "$tmpdir"' EXIT

git clone --no-checkout --depth=1 --filter=tree:0 'https://github.com/git/git' "$tmpdir"

subdir=contrib/credential/libsecret
git -C "$tmpdir" sparse-checkout set "$subdir"
git -C "$tmpdir" checkout

cd "$tmpdir/$subdir"
make && cp -v git-credential-libsecret "$XDG_CACHE_HOME/bin"
