# vim: filetype=conf foldmethod=marker

ENVIRONMENT_D_LOADED="1"
EDITOR="vim"
LESS="-x4 -iRw"
PAGER="less"
VISUAL="nvim"

# => wine --------------------------------------------------------------------------------------------------------- {{{1

# WINEPREFIX="${XDG_CACHE_HOME}/wine/default-x32"
# WINEARCH=win32

# => X11 settings ------------------------------------------------------------------------------------------------- {{{1

#XINITRC="${XDG_CONFIG_HOME}/.config/x11/xinitrc"
#XSERVERRC="${XDG_CONFIG_HOME}/x11/xserverrc"

### this might break lightdm (and xrdp)
#XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
#ICEAUTHORITY="${XDG_RUNTIME_DIR}/ICEauthority"

# => does not work ------------------------------------------------------------------------------------------------ {{{1

# GTK_RC_FILES="${XDG_CONFIG_HOME}/x11/gtk1rc"
# GTK2_RC_FILES="${XDG_CONFIG_HOME}/x11/gtk2rc"
# ERRFILE="${XDG_CACHE_HOME}/x11/xsession-errors"
