# vim: filetype=conf foldmethod=marker

BSPWM_SOCKET="${XDG_RUNTIME_DIR}/bspwm.default"
FZF_DEFAULT_OPTS_FILE="${XDG_CONFIG_HOME}/fzfrc"
FUSE3_P7ZIP_FORMATS="Iso:Udf:*:APM:GPT"
GROFF_TMPDIR="/tmp"
INPUTRC="${XDG_CONFIG_HOME}/inputrc"
MISE_GITHUB_USE_GIT_CREDENTIALS="true"
MYSQL_HISTFILE="${XDG_STATE_HOME}/mysql_history"
PARALLEL_HOME="${XDG_CONFIG_HOME}/parallel"
PINENTRY_KDE_USE_WALLET="1"
REDISCLI_HISTFILE="${XDG_STATE_HOME}/redis_history"
RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgreprc"
USRTMP="${HOME}/.local/no-cow/tmp"
VAGRANT_DOTFILE_PATH="${XDG_DATA_HOME}/vagrant"
WGETRC="${XDG_CONFIG_HOME}/wgetrc"
