# vim: filetype=conf foldmethod=marker

MISE_CEILING_PATHS="${HOME}:${XDG_CONFIG_HOME}"
MISE_ENV="${USER}"
MISE_GITHUB_USE_GIT_CREDENTIALS="true"
MISE_IGNORED_CONFIG_PATHS="/media:/tmp:/var:${HOME}/.local"
