# vim: filetype=conf foldmethod=marker

# Some modules stupidly use `JSON` module instead of `JSON::MaybeXS`
# which has absolutely weird default load module order.
# This is to make sure `Cpanel::JSON::XS` is preferred even when `JSON` is used:
PERL_JSON_BACKEND="Cpanel::JSON::XS,JSON::XS,JSON::PP"
