#!/usr/bin/env bash

set -Eeuo pipefail

function fatal() {
    echo "fatal:" "$@" >&2; exit 1
}

credentials="$(cred 'https://gitlab.com')"

password="$(echo "$credentials" | grep -Pom1 '^password=\K.+' 2>/dev/null || true)"
[[ -n "$password" ]] || fatal 'failed to retrieve access token'
username="$(echo "$credentials" | grep -Pom1 '^username=\K.+' 2>/dev/null || true)"

jq -Sn --arg access_token "$password" --arg username "$username" '{
  "Secret": $access_token,
  "Username": $username
}'
