#!/usr/bin/env bash
# shellcheck disable=SC2154

set -Eeuo pipefail

[[ -x "$(command -v argc)" ]] || {
    echo "'argc' helper command is required, install from https://github.com/sigoden/argc" >&2
    exit 2
}

# @describe ABSTRACT:
#   Opinionated wrapper over main qemu commands
#
# SYNOPSIS:
#   emu run arch-linux.iso
#
# LICENSE:
#   GPL-2.0-or-later
#   🄯 2025 Andrew Grechkin

# @meta version 1.0.0
# @meta combine-shorts
# @meta require-tools qemu-system-x86_64

shopt -s nullglob

default_args=(
    -audiodev "pa,id=snd0"
    -cpu host
    -device "ich9-intel-hda"
    -device "hda-output,audiodev=snd0"
    -device "qemu-xhci,id=xhci"
    -device "vhost-vsock-pci,id=vhost-vsock-pci0,guest-cid=5"
    -smbios "type=11,value=io.systemd.credential.binary:ssh.authorized_keys.root=$(base64 ~/.ssh/id_ed25519.pub)"
    -display "gtk,zoom-to-fit=on"
    -enable-kvm
    -k en-us
    -m 4G
    -nic "user,model=virtio-net-pci"
    -no-reboot
    -smp 2
    -vga virtio
    # -vga std
)

# @cmd
# @describe
# execute VM
function run() { :; }

# @cmd
# @arg    file!         Image
# @flag   -b --bios     BIOS
# @flag   -u --usb      Attach usb stick
# @meta  default-subcommand
# @describe
# execute VM with an image file
function run::file() {
    local type
    if [[ -n "${argc_bios:-}" ]]; then
        type=bios
    else
        type='uefi'
        options+=(
            -bios /usr/share/ovmf/x64/OVMF.4m.fd
        )
    fi

    if [[ "$argc_file" = *.iso ]]; then
        options+=(
            -drive "file=${argc_file},if=virtio,index=1,media=cdrom"
        )
        iso_name=$(basename "$1")
        iso_dir=$(dirname "$1")

        if [[ -n "${argc_usb:-}" ]]; then
            usb_name="${iso_name/.iso/}.$type.usb.qcow2"
            usb_path="$iso_dir/$usb_name"

            [[ -f "$usb_path" ]] || qemu-img create -f qcow2 "$usb_path" 8G

            options+=(
                -device "usb-storage,bus=xhci.0,drive=stick"
                -drive  "file=$usb_path,if=none,id=stick,format=qcow2"
            )
        fi

        if [[ -n "${file:-}" ]]; then
            options+=(
                -drive "file=${file},if=virtio,index=0,media=disk,format=raw"
            )
        else
            qcow_name="${iso_name/.iso/}.$type.0-nvme.qcow2"
            qcow_path="$iso_dir/$qcow_name"
            [[ -f "$qcow_path" ]] || qemu-img create -f qcow2 "$qcow_path" 128G
            options+=(
                # -drive "file=$QCOW_PATH,if=virtio,index=0,media=disk,format=qcow2"
                -device "nvme,serial=deadbeef,drive=nvm"
                -drive  "file=$qcow_path,if=none,id=nvm"
            )
        fi
    elif [[ "$argc_file" =~ usb.qcow2$ ]]; then
        options+=(
            -device "usb-storage,bus=xhci.0,drive=stick"
            -drive  "file=$argc_file,if=none,id=stick,format=qcow2"
        )
    elif [[ "$1" =~ qcow2$ ]]; then
        name="${1%.qcow2}"

        index=0
        for file in "${name::-1}"*.qcow2; do
            [[ "$file" =~ nvme\.qcow2$ ]] && continue
            options+=(-drive "file=$file,if=virtio,index=$index,media=disk,format=qcow2")
            index=$(( ++index ))
        done

        name="${name%-nvme}"
        args=(
            -device "nvme,serial=deadbeef,drive=nvm"
        )
        for file in "${name::-1}"*-nvme.qcow2; do
            options+=(-drive "file=$file,if=none,id=nvm")
        done
    else
        options+=(
            -drive "file=$argc_file,if=virtio,index=0,media=disk,format=raw"
        )
    fi

    args=(
        "${default_args[@]}"
        "${options[@]}"
    )
    # -cdrom "$1"
    # -serial stdio
    # -virtfs "local,path=$HOME/.cache,mount_tag=host0,security_model=passthrough,id=host0"
    # -smbios "type=11,value=io.systemd.credential.binary:ssh.authorized_keys.root=$(base64 ~/.ssh/id_ed25519.pub)"
    # -smbios "type=11,value=io.systemd.credential.binary:ssh.authorized_keys.dummy=$(base64 ~/.ssh/id_ed25519.pub)"
    # -netdev "bridge,id=hn0"
    # -device "virtio-net-pci,netdev=hn0,id=nic1"
    # -nic "tap,ifname=tap0,romfile=,script=no,downscript=no"
    # -device "virtio-net,netdev=network0"
    # -netdev "tap,id=network0,ifname=tap0,script=no,downscript=no"
    # -device "e1000,netdev=network0,mac=52:55:00:d1:55:01"
    # -nic "user,model=virtio-net-pci,hostfwd=tcp::2222-:22"

    exec qemu-system-x86_64 "${args[@]}"
    # -drive file=$(QCOW2_IMAGE),if=ide,index=0,media=disk,format=qcow2 \
        # qemu-system-x86_64                                                   \
        #     -device virtio-scsi-pci,id=scsi0                                 \
        #     -device "scsi-${mediatype%rom},bus=scsi0.0,drive=${mediatype}0"  \
        #     -drive "id=${mediatype}0,if=none,format=raw,media=${mediatype/hd/disk},read-only=on,file=${image}" \
        #     -device virtio-net-pci,romfile=,netdev=net0 -netdev user,id=net0,hostfwd=tcp::60022-:22 \
        #     -machine type=q35,smm=on,accel=kvm,usb=on,pcspk-audiodev=snd0    \
        #     -global ICH9-LPC.disable_s3=1                                    \
        #     "${qemu_options[@]}"                                             \
        # -display "sdl"
}

# @cmd
# @arg    file                 Image
# @option -v --vendor=0x090c   USB stick vendor
# @option -p --product=0x1000  USB stick vendor
# @describe
# execute VM on a USB stick
function run::stick() {
    # qemu-system-x86_64 -device usb-host,help

    if [[ -n "${argc_file:-}" ]]; then
        options+=(
            -drive "file=$argc_file,if=virtio,index=1,media=cdrom"
        )
    fi

    args=(
        -bios /usr/share/ovmf/x64/OVMF.4m.fd
        "${default_args[@]}"
        -device "usb-host,vendorid=${argc_vendor},productid=${argc_product}"
        # -device "usb-host,hostbus=$BUS,hostport=$PORT"
        "${options[@]}"
    )

    exec qemu-system-x86_64 "${args[@]}"
}

# @cmd
# @arg    file                 Image
# @describe
# mount file
function mnt() {
    sudo modprobe nbd max_part=2
    sudo qemu-nbd --connect=/dev/nbd0 "$1"
    sudo mount /dev/nbd0p1 /mnt
    sudo cryptsetup open /dev/nbd0p2 tails
    mkdir -p /tmp/mnt
    sudo mount /dev/mapper/tails /tmp/mnt
}

eval "$(argc --argc-eval "$0" "$@")"
