#!/usr/bin/env bash

set -Eeuo pipefail

url="${1?url must be provided as the first and only argument}"
url="${url%.git}"

if [[ "$url" =~ :\/\/ ]]; then
    # use git credential itself to parse url by using echo helper
    args=(
        -c credential.helper=
        -c credential.helper=echo
        -c credential.interactive=false
        -c credential.useHttpPath=true
    )
    echo "url=$url" | GIT_CONFIG_NOSYSTEM=1 git "${args[@]}" credential fill
else
    # TODO: this might be too primitive to parse git urls for SSH protocol this way
    IFS="@" read -r user url <<< "$url"
    [[ -n "$url" ]] || { echo "error: cannot parse url (<user>@ must prepepend the host): $1"; exit 1; }

    IFS=":" read -r host path <<< "$url"
    [[ -n "$path" ]] || { echo "error: cannot parse url (:<path> must follow the host): $1"; exit 1; }

    if [[ -n "${host:-}" ]]; then
        echo "protocol=git"
        echo "host=$host"
        echo "path=$path"
        echo "username=$user"
    else
        echo "error: cannot parse url: $1"
        exit 1
    fi
fi
