#!/usr/bin/env bash

set -Eeuo pipefail

# @describe simple git credentials helper for `pass` password manager

# @meta version 1.0.0
# @meta combine-shorts
# @meta require-tools jq,pass

# @arg    command=get  Command to execute
# @option -k --key     Expect secret to be a value of a key in a JSON
# @option -p --path    Explicit path to the secret

[[ -x "$(command -v argc)" ]] || {
    echo "'argc' helper command is required, install from https://github.com/sigoden/argc" >&2
    exit 2
}

eval "$(argc --argc-eval "$0" "$@")"

# => -------------------------------------------------------------------------------------------------------------- {{{1

# only get command is supported
[[ "${argc_command:-}" == 'get' ]] || exit

# stdin lines to variables
while read -r line; do
    declare -- "$line"
done

[[ -z "${protocol:=https}" || -z "${host:-}" || -z "${username:=$USER}" ]] && exec echo "continue=1"

argc_path="${argc_path:-"$protocol/$host/$username"}"

if ! data="$(pass show "$argc_path" 2>/dev/null)"; then
    echo "> $(basename "$0") unable to fetch secret: $argc_path" >&2
    echo "continue=1"
    exit 0
fi

echo "protocol=$protocol"
echo "host=$host"
[[ "$data" =~ "username=" ]] || echo "username=$username"

if [[ -n "${argc_key:-}" ]] && value=$(jq -r --arg key "$argc_key" '.[$key] // empty' <<< "$data" 2>/dev/null) && [[ -n "$value" ]]; then
    echo "password=$value"
elif [[ "$data" =~ "password=" ]]; then
    echo "$data"
else
    echo "password=$(head -1 <<< "$data")"
fi
