#!/usr/bin/env bash

# ABSTRACT: simple git credentials helper for vault oidc

set -Eeuo pipefail

# only get command is supported
[[ "${1:-}" == 'get' ]] || exit

# expose input key=value pars as variables
while read -r line; do
    declare -- "$line"
done

[[ "${protocol:-}" != 'https' ]] && exec echo 'continue=1'

function fatal() {
    echo "fatal:" "$@" >&2; exit 1
}

port='8250' # port is hardcoded because contract
payload="$(jq -cn --arg port "$port" '{redirect_uri: "http://localhost:\($port)/oidc/callback"}')"
url="$(curl --fail-with-body -sXPOST "https://${host?'host must be provided'}/v1/auth/oidc/oidc/auth_url" -H "content-type:application/json" --data "$payload" | jq -r '.data.auth_url // empty')"
[[ -n "$url" ]] || fatal 'unable to fetch auth URL'

echo "> $(basename "$0") requesting refresh token from:" >&2
echo "  $url" >&2

# this is the most portable way of starting browser I know of
git web--browse "$url" &>/dev/null || fatal 'unable to start request in browser to fetch refresh token'

{ enable accept && accept -b '127.0.0.1' -t 60 "$port"; } || fatal "unable to bind socket on port: $port"
[[ -n "${ACCEPT_FD:-}" ]] || fatal 'unable to accept on socket'

# quite simple HTTP 1.1 parser, targets only known standard existing contract which is not going to change
IFS=$'\r\n' read -r -u "$ACCEPT_FD" res
while IFS=$'\r\n' read -r -u "$ACCEPT_FD" header; do
    if [[ -z "$header" ]]; then
        html='<html><head></head><body onload="waitFiveSec()">
        <h1>Request is successfully processed, this page will close automatically in 5 sec</h1>
        <script>function waitFiveSec() { setTimeout(function() { window.close() }, 5000) }</script>
        </body></html>'
        size=$(echo -n "$html" | wc -c)
        echo -e "HTTP/1.1 200 OK\r\nContent-Type:text/html;charset=utf-8\r\nContent-Length:$size\r\n\r\n$html" >&"$ACCEPT_FD"
        break
    fi
done

exec {ACCEPT_FD}>&- # close connection

[[ -n "${res:-}" ]] || fatal 'unable to fetch response from OICD provider'

query="$(grep -Pom1 '\/oidc\/callback\?\K\S+' <<< "$res")"
if ! creds="$(curl --fail-with-body -s "https://$host/v1/auth/oidc/oidc/callback?$query")"; then
    echo "request to fetch access token failed with response:" >&2
    jq <<< "$creds" >&2
    exit 1
fi

password="$(jq -r '.auth.client_token // empty' <<< "$creds")"
username="$(jq -r '.request_id // empty' <<< "$creds")"
[[ -n "$username" && -n "$password" ]] || fatal 'unable to fetch username or/and password'

lease_duration="$(jq -r '.auth.lease_duration // empty' <<< "$creds")"
[[ -n "$lease_duration" ]] && echo "password_expiry_utc=$(date -d "+$lease_duration seconds" +%s)"
echo "protocol=$protocol"
echo "host=$host"
echo "username=$username"
echo "password=$password"
