#!/usr/bin/env bash

set -Eeuo pipefail

# ABSTRACT: simple git credentials helper just for echoing input

# only get command is supported
[[ "${1:-}" == 'get' ]] || exit

if [[ -n "${payload:=$(</dev/stdin)}" ]]; then
    cat <<< "$payload"
    [[ "$payload" =~ "username=" ]] || echo username=
    [[ "$payload" =~ "password=" ]] || echo password=
fi
