#!/usr/bin/env bash

# ABSTRACT: simple git credentials helper for `pass` password manager

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'k:p:' --longoptions 'key:,path:' -- "$@")
eval set -- "$args"

while ((1)); do
    case "$1" in
        -k | --key) key="$2"; shift 2 ;;
        -p | --path) pth="$2"; shift 2 ;;
        --) shift; break ;;
    esac
done

# only get command is supported
[[ "${1:-}" == 'get' ]] || exit

while read -r line; do
    IFS='=' read -r k v <<< "$line"
    eval "$k='$v'"
done

if [[ -z "${pth:-}" ]] && [[ -z "${host:-}" || -z "${username:=$USER}" || -z "${protocol:=https}" ]]; then
    echo "continue=1"
    exit 0
fi

if data="$(pass show "${pth:-"token/$protocol/$host/$username"}" 2>/dev/null)"; then
    echo "protocol=$protocol"
    echo "host=$host"
    [[ "$data" =~ username= ]] || echo "username=$username"

    if [[ -n "${key:-}" ]] && value=$(jq -r --arg key "$key" '.[$key] // empty' <<< "$data" 2>/dev/null) && [[ -n "$value" ]]; then
        echo "password=$value"
    elif [[ "$data" =~ password= ]]; then
        echo "$data"
    else
        echo "password=$data"
    fi

    exit 0
fi

echo "continue=1"
