#!/usr/bin/env bash

set -Eeuo pipefail

function fatal() {
    echo "fatal:" "$@" >&2; exit 1
}

relpath="${1?password path is required}"
store=${PASSWORD_STORE_DIR:-${XDG_DATA_HOME}/password-store}

cd "$store" || fatal "unable to set workdir: $store"

outpath="$(realpath -m --relative-base="$store" "$relpath")"
[[ "$outpath" == /* ]] && fatal 'absolute path provided and it is not in password store'

outpath="${outpath%%.gpg}.gpg"

mkdir -p "$(dirname "$outpath")"

IFS=',' read -r -a recipients <<< "${GPG_RECIPIENTS:-}"

gpg --armor --encrypt --default-recipient-self "${recipients[@]/#/'--recipient='}" --output "$outpath" -
