#!/usr/bin/env bash

set -Eeuo pipefail

function fatal() {
    echo "fatal:" "$@" >&2; exit 1
}

credentials="$(cred "$VAULT_ADDR")"

password="$(echo "$credentials" | grep -Pom1 '^password=\K.+' 2>/dev/null || true)"
[[ -n "$password" ]] || fatal 'failed to retrieve access token'

echo -n "$password"
