#!/usr/bin/env bash

set -Eeuo pipefail

function fatal() {
    echo "fatal:" "$@" >&2; exit 1
}

password="$(credp "$VAULT_ADDR")"
[[ -n "$password" ]] || fatal 'failed to retrieve access token'

echo -n "$password"
