#!/usr/bin/env bash

set -Eeuo pipefail

file="$XDG_STATE_HOME/zsh/history@$HOSTNAME"

fzf_args=(
	--bind="change:reload(rg -Pa --color=always {q} '$file')"
	--bind="ctrl-m:become(echo {q})"
	--bind="start:change-query()"
	--phony
	--print-query
	--query="."
	--reverse
)

if regex="$(echo 'loading...' | fzf "${fzf_args[@]}")"; then
	rg -Pa --no-line-number "$regex" "$file"
fi
