#!/usr/bin/env bash

set -Eeuo pipefail

# LC_ALL=C grep -P "[\x80-\xFF]" "$HISTFILE"
# grep -iP "\b[[:xdigit:]]{40}\b" "$HISTFILE"

file="$XDG_STATE_HOME/zsh/history@$HOSTNAME"

temp_file=$(mktemp -u)

function finish {
	rm -f "$temp_file"
}
trap finish EXIT

fzf_args=(
	--bind="ctrl-m:become(cat {+f})"
	--bind="tab:toggle-out,shift-tab:toggle-in,ctrl-a:toggle-all"
	--multi
	--reverse
	--tiebreak="begin,chunk"
	--track
)

lines="$(LC_COLLATE=C sort < "$file" | fzf "${fzf_args[@]}")"

echo "Pruning history for whole lines: $(wc -l <<< "$lines")"
cp -f "$file" "$file.prune.bak"

cp -f "$file" "$temp_file"
echo "Lines before: $(wc -l < "$temp_file")"
grep -vaxF -f <(echo "$lines") "$temp_file" | sponge "$temp_file"
echo "Lines after: $(wc -l < "$temp_file")"
mv -f "$temp_file" "$file"
