#!/usr/bin/env zsh

set -Eo pipefail

# fetcher=(
# 	apt-file search -x
# )

fetcher=(
	pacman -F -x
)

fzf_cmd=(
	fzf
	--ansi
	--bind="ctrl-l:reload(${fetcher[*]} {q})"
	--bind="change:reload(${fetcher[*]} {q})"
	# --bind="change:transform-query(echo {q} | sed \"s/^\///\")+reload(${fetcher[*]} {q})"
	--bind="start:reload(${fetcher[*]} core)"
	--disabled
	--no-sort
	--reverse
)

"${fzf_cmd[@]}"
