#!/usr/bin/env bash

set -Eeuo pipefail

export FZF_RELOAD_CMD="env | sort | sed 's/=.*//'"
source "$HOME/.local/lib/shell/fzf.bash"

# shellcheck disable=SC2016
preview_quoted='echo -n "\"${}\""'
# shellcheck disable=SC2016
preview='echo "${}"'

fzf_args=(
	--bind="alt-i:execute(bash -c 'echo -n {}=; $preview_quoted' | ${PAGER:-less})"
	--bind="ctrl-m:become(bash -c '$preview' | tee >(trim-whole | clipcopy))"
	--bind="ctrl-y:execute-silent(bash -c 'echo -n {}=; $preview_quoted' | clipcopy)"
	--header-lines=0
	--preview-window="right:60%:border-left:wrap:nohidden"
	--preview="bash -c '$preview'"
)

eval "$FZF_RELOAD_CMD" | fzf-exec "${fzf_args[@]}"
