#!/usr/bin/env bash

set -Eeuo pipefail

# ABSTRACT: convert shell-encoded tokens provided via cmd line or stdin to lines without quotes

current_script="$(basename "$0")"
if [[ "$current_script" =~ 0$ ]]; then
    delim='\0'
else
    delim='\n'
fi

if [[ -z "$*" && ! -t 0 ]]; then
    eval set -- "$(</dev/stdin)"
fi

printf '%s'"$delim" "$@"
