#!/usr/bin/env bash

set -Eeuo pipefail

current_script="$(basename "$0")"
if [[ "$current_script" =~ ya?ml$ ]]; then
    args=(-l YAML)
elif [[ "$current_script" =~ json$ ]]; then
    args=(-l JSON)
elif [[ "$current_script" =~ tsv$ ]]; then
    args=(-l TSV)
else
    args=()
fi

[[ -z "$*" ]] && args+=(--paging=never --decorations=never)

PATH=${PATH//"$(dirname "$0"):"/}

exec bat --color=always --theme=OneHalfDark "${args[@]}" "$@"
