#!/usr/bin/env -S bash -Eeuo pipefail
# shellcheck disable=SC2154

type -P argc &>/dev/null || {
    echo "'argc' helper command is required, install from https://github.com/sigoden/argc" >&2
    exit 2
}

# @meta combine-shorts
# @meta version 1.0.0

# @describe ABSTRACT:
#   Pretty-print JSON data with optional colorization and pagination
#
# SYNOPSIS:
#   echo '{"example": true}' | json-pretty --paging=never
#
# DESCRIPTION:
#   Read JSON input from files or STDIN, then pretty-print it with formatting (YAML preferred),
#   colorization and optional pagination

# @arg    file                             File to process, uses STDIN if not provided
# @flag   -C $FORCE_COLOR                  Force color, even if not a TTY
# @flag   -P $FORCE_PAGING                 Force paging, even if not a TTY
# @flag   -n --no-filename                 Don't show filename even if it's known
# @flag   -p                               Force paging, even if not a TTY (deprecated, backward compatibility)
# @option -c --color[=auto|never|always]   Control color mode
# @option -f --filename                    Explicitly provide name of the file for display
# @option    --paging[=auto|always|never]  Control paging

eval "$(argc --argc-eval "$0" "$@")"

[[ -n "${argc_C:-}" ]] && argc_color='always'
[[ -n "${argc_P:-}" || -n "${argc_p:-}" ]] && argc_paging='always'

if [[ "$argc_paging" != 'never' ]] && [[ -t 1 || "$argc_paging" == 'always' ]]; then
    page=("|" "${PAGER:-less}")
fi

if type -P json2yaml && type -P perl && \
    [[ -n "$(perl -e 'print $] >= 5.036')" && -n "$(perl -MYAML::XS -e 'print $YAML::XS::VERSION' 2>/dev/null)" ]]; then
    format=("json2yaml")
    lang="yaml"
elif type -P jaq; then
    format=("jaq --to yaml -S")
    colorize=("-C")
elif type -P yq; then
    format=("yq -P -p=json -o yaml 'sort_keys(..)'")
    lang="yaml"
else
    format=("jq --indent 2 -S")
    colorize=("-C")
fi &>/dev/null

if [[ "$argc_color" != 'never' ]] && [[ -t 1 || "$argc_color" == 'always' ]]; then
    if [[ -z "${colorize[*]}" ]] && type -P bat &>/dev/null; then
        if [[ -n "${argc_no_filename:-}" ]]; then
            bat_args=(--style=plain)
        else
            if [[ -n "${argc_filename:-}" ]]; then
                bat_args=(--style=header "--file-name=${argc_filename}")
            else
                bat_args=(--style=header "--file-name=STDIN.${lang:-json}")
            fi
        fi

        colorize=("|" "bat --wrap=never -l ${lang@Q} --color=${argc_color} ${bat_args[*]@Q}")

        if [[ -n "${page[*]}" ]]; then
            page=(--paging=always)
        fi
    fi
else
    colorize=()
fi # NOTE: silencing by redirecting to /dev/null here will break TTY detection

cat "${argc__positionals[@]}" | eval "${format[*]}"' '"${colorize[*]}"' '"${page[*]}"
