#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'e' --longoptions 'escape' -- "$@")
eval set -- "$args"

while ((1)); do
	case "$1" in
		-e | --escape) escape='1'; shift ;;
		--) shift; break ;;
	esac
done

quote-if-necessary() {
	[[ -n "$1" ]] || return 0

	local escaped
	escaped=$(printf '%q' "$1")

	if [[ "$1" == "$escaped" ]]; then
		printf '%s' "$1"
	else
		if [[ "${escape:-}" == "1" ]]; then
			printf '%s' "$escaped"
		else
			printf '%s' "${line@Q}"
		fi
	fi
}

while read -r line || [[ -n "$line" ]]; do
	[[ -n "$line" ]] && { quote-if-necessary "$line"; break; }
done

while read -r line || [[ -n "$line" ]]; do
	[[ -n "$line" ]] && { echo -n ' ' && quote-if-necessary "$line"; }
done

# mapfile -t DATA
# echo "${DATA[@]@Q}"
