#!/usr/bin/env -S perl -CALS -M Digest::MD5=md5_hex

use v5.36;

my %index;

while (defined(my $line = <<>>)) {
    chomp $line;
    my $md5 = md5_hex($line);
    do {say {*STDOUT} $line; undef $index{$md5}} unless exists $index{$md5};
}

__END__
