#!/usr/bin/env -S perl -n
use v5.36;

## no critic [Variables::ProhibitPunctuationVars]

$_ = builtin::trim($_);

length && do {
    $. > 1
        and print ' ';
    print;
};

__END__

# perl is much more efficient here
##!/usr/bin/env bash
#
#set -Eeuo pipefail
#
## while read LINE; do
## 	echo -n " ${(q)LINE}"
## done
#
#mapfile -t DATA
#
## do not quote DATA to force bash eliminate empty lines
## shellcheck disable=SC2086
#echo ${DATA[*]}
