#!/usr/bin/env bash

set -Euo pipefail

DATETIME=$(date --rfc-3339=ns)

CODEPAGE=$1
shift

for FILE in "$@"; do
	if text-decode --codepage="$CODEPAGE" "$FILE" >"${FILE}.${DATETIME}.encoded"; then
		mv -f "${FILE}.${DATETIME}.encoded" "$FILE"
		echo "Successfully reencoded from $CODEPAGE: $FILE"
	else
		echo "Failed to reencode: '$FILE'"
		rm -f "${FILE}.${DATETIME}.encoded"
	fi
done
