#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'cnp' --longoptions 'number,paging:' -- "$@")
eval set -- "$args"

color='auto'
paging='auto'

while ((1)); do
    case "$1" in
        -c) color="always"; shift ;;
        -n) add_args+=(-n); shift ;;
        -p) paging="always"; shift ;;
        --number) add_args+=(--number); shift ;;
        --paging) paging="$2"; shift 2 ;;
        --) shift; break ;;
    esac
done

cmd=(
    column --table --separator=$'\t' --output-separator=$'\t' "$@"
)

if [[ "$paging" != 'never' ]] && [[ "$paging" == 'always' || -t 1 ]]; then
    LESS="${LESS:-"-x4 -iRSw --mouse"}"
    LESS+=' --header=1'
    # the below condition disables arrow scrolling for some reason
    # [[ "$paging" == 'always' ]] || LESS+=' --quit-if-one-screen'
    "${cmd[@]}" | colored-tsv "${add_args[@]}" | less || true
elif [[ "$color" == "always" ]]; then
    "${cmd[@]}" | colored-tsv "${add_args[@]}"
else
    exec "${cmd[@]}"
fi
