#!/usr/bin/env -S bash -Eeuo pipefail
# shellcheck disable=SC2016

source "$(dirname "$0")/test.bash"

read -r -d '' input <<'EOF' || true
{
  "user": {
    "profile": {
      "name": "John Doe",
      "address": {
        "city": "New York",
        "zipcode": "10001"
      }
    }
  }
}
EOF

read -r -d '' expected <<'EOF' || true
"New York"
EOF

filter='include "common"; $input | get_in(["user", "profile", "address", "city"])'

tests "'get_in'" "$filter" "$input" "$expected" 'retrieves nested value from path'
