# vim: filetype=dockerfile

FROM docker.io/library/archlinux:base-devel

LABEL                                                               \
    com.github.containers.toolbox="true"                            \
    name="arch-toolbox"                                             \
    summary="Base image for creating Arch Linux Toolbox containers" \
    usage="This image is meant to be used with the toolbox command" \
    version="base-devel"

RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox
RUN pacman -Syu --needed --noconfirm \
    base                    \
    base-devel              \
    flatpak-xdg-utils       \
    nss-mdns                \
    plocate                 \
    sudo                    \
    xorg-xauth              \
    ansible                 \
    fzf                     \
    reflector               \
    tmux                    \
    vim                     \
    xsel                    \
    zsh                     \
    && yes | pacman -Scc    \
    && sed -i 's|.*\(en_US\.UTF-8\)|\1|' /etc/locale.gen \
    && locale-gen

RUN pacman -Syu --noconfirm \
    man-db                  \
    man-pages               \
    && yes | pacman -Scc    \
    && mandb

ENV LC_ALL=en_US.UTF-8
