#!/usr/bin/env bash

set -Eeuo pipefail

ecode='0'
while IFS= read -r -d '' path; do
    [[ -d "$path" || "$path" =~ \.rec$ || "$path" =~ \.tsv$ ]] && continue

    if grep -PIHn --color=always '[^\t\#]\t+' "$path"; then
        ecode='1'
    fi
done < <(git diff --cached --name-only -z --diff-filter=AMR)

[[ "$ecode" == '0' ]] || echo '^^^ tabs might be only at beginnings of lines ^^^'

exit "$ecode"
