#!/usr/bin/env perl

use v5.28;
use warnings;

my $message = <>;
my $regex   = qr{ \[ DEP- \d+ \] }xms;

if ($message !~ $regex) {
    die "[POLICY] Your message is not formatted correctly. Expected [DEP-xxx] ticket reference\n";
}
