---
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:vue-scoped-css/vue3-recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - html
  - vue
  - align-assignments
settings:
  html/html-extensions: [.html, .html.ep]
rules:
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  curly:
    - error
    - multi-or-nest
    - consistent
  dot-location:
    - error
    - property
  dot-notation:
    - error
  eqeqeq:
    - error
  func-call-spacing:
    - error
    - never
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  no-floating-decimal:
    - error
  no-implicit-coercion:
    - error
  no-invalid-this:
    - error
  no-useless-return:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  no-unused-vars:
    - error
    - vars: local
      varsIgnorePattern: app
  key-spacing:
    - error
    - mode: minimum
      align: value
  spaced-comment:
    - error
    - always
  align-assignments/align-assignments:
    - 2
    - requiresOnly: false
  vue/html-indent:
    - error
    - 4
  vue/component-definition-name-casing:
    - warn
    - kebab-case
