---
bracketSpacing: false
htmlWhitespaceSensitivity: ignore
overrides:
  - files: ['*.yaml', '*.yml']
    options:
      tabWidth: 2
printWidth: 120
semi: false
singleQuote: true
tabWidth: 4
trailingComma: all
# vueIndentScriptAndStyle: true
