---
bracketSpacing: false
htmlWhitespaceSensitivity: ignore

overrides:
  - files: ['*.yaml', '*.yml']
    options:
      tabWidth: 2
  - files: ['*.html', '*.html.ep']
    options:
      parser: html

printWidth: 120
semi: false
singleQuote: true
tabWidth: 4
trailingComma: all
vueIndentScriptAndStyle: true
