#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -b &

bspc monitor DP-3 -d 1 2 3
bspc monitor -d 4 5 6 7 8 9 0

bspc config border_width            2
bspc config borderless_monocle      true
bspc config bottom_padding          42
bspc config center_pseudo_tiled     false
bspc config focus_follows_pointer   true
bspc config gapless_monocle         true
bspc config honor_size_hints        true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true
bspc config split_ratio             0.6
bspc config window_gap              0

bspc rule -r '*'
bspc config external_rules_command "$(realpath ~/.local/script/bspwm-external-rules)"
bspc rule -a '*:*:Picture in Picture' state=floating sticky=on rectangle=480x270-522-330
bspc rule -a 'mpv'                    state=floating sticky=on rectangle=480x270-522-330
bspc rule -a 'pinentry'               state=floating sticky=on
bspc rule -a 'gpclient'               state=floating sticky=on

bspc rule -a 'Gimp'          desktop='^8' state=floating follow=on
bspc rule -a 'Chromium'      desktop='^1'
bspc rule -a 'Google-chrome' desktop='^1'
bspc rule -a 'Opera'         desktop='^2'
bspc rule -a 'Screenkey'     manage=off
