#!/usr/bin/env bash

BACKGROUND_APPS=(
	sxhkd
	picom
	redshift
	"$(realpath ~/.local/script/bspwm-watch-monitor)"
)

for BAPP in "${BACKGROUND_APPS[@]}"; do
	pgrep -x "$BAPP" > /dev/null || "$BAPP" &
done

bspc config border_width            2
bspc config borderless_monocle      true
bspc config bottom_padding          42
bspc config center_pseudo_tiled     false
bspc config focus_follows_pointer   true
bspc config gapless_monocle         true
bspc config honor_size_hints        true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true
bspc config split_ratio             0.6
bspc config window_gap              0

bspc rule -r '*'
bspc config external_rules_command "$(realpath ~/.local/script/bspwm-external-rules)"
bspc rule -a '*:*:Picture in Picture' state=floating sticky=on rectangle=564x317-600-360
bspc rule -a 'floating'               state=floating
bspc rule -a 'gpclient'               state=floating sticky=on
bspc rule -a 'mpv'                    state=floating sticky=on rectangle=564x317-600-360
bspc rule -a 'pinentry'               state=floating sticky=on

bspc rule -a '*:*:Zoom - Licensed Account' desktop='6'
bspc rule -a '*:*:Zoom Meeting'            desktop='6'
bspc rule -a 'Chromium'                    desktop='1'
bspc rule -a 'Gimp'                        desktop='8' state=floating follow=on
bspc rule -a 'Google-chrome'               desktop='1'
bspc rule -a 'Opera'                       desktop='2'
bspc rule -a 'Screenkey'                   manage=off
bspc rule -a 'Steam'                       desktop='6'
bspc rule -a 'dolphin'                     desktop='4'
bspc rule -a 'VirtualBox Manager'          desktop='4'
bspc rule -a 'VirtualBoxVM'                desktop='5'
