#!/usr/bin/env bash

exec 1>"${XDG_RUNTIME_DIR}/bspwm.log" 2>&1
set -x

BACKGROUND_APPS=(
    sxhkd
    picom
    redshift
    "$(realpath ~/.local/script/bspwm-init)"
)

echo 'Starting background apps...'
for BAPP in "${BACKGROUND_APPS[@]}"; do
    if [[ "$BAPP" == *"/"* ]]; then
        OPT=-xf
    else
        OPT=-x
    fi
    pgrep "$OPT" "$BAPP" >/dev/null || {
        echo "  Starting $BAPP"
        "$BAPP" &
    }
done

bspc config border_width            2
bspc config borderless_monocle      true
bspc config bottom_padding          42
bspc config center_pseudo_tiled     false
bspc config focus_follows_pointer   false
bspc config gapless_monocle         true
bspc config honor_size_hints        true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true
bspc config split_ratio             0.6
bspc config window_gap              0

tiny='854x480'
small='1024x576'
normal='1280x720'
big='1600x900'

if res="$(xdpyinfo | grep -oP 'dimensions:\s+\d+x\K\S+' 2>/dev/null)"; then
    if ((res >= 1920)); then
        tiny='1024x576'
        small='1280x720'
        normal='1920x1080'
        big='2400x1400'
    fi
fi

bspc rule -r '*'
bspc config external_rules_command "$(realpath ~/.local/script/bspwm-external-rules)"
bspc rule -a '*:*:Picture in Picture' state=floating sticky=on
bspc rule -a 'TermFloatingTiny'       state=floating center=on "rectangle=$tiny+0+0"
bspc rule -a 'TermFloatingSmall'      state=floating center=on "rectangle=$small+0+0"
bspc rule -a 'TermFloatingBig'        state=floating center=on "rectangle=$big+0+0"
bspc rule -a 'TermFloating'           state=floating center=on "rectangle=$normal+0+0"
bspc rule -a 'FloatingNormal'         state=floating center=on "rectangle=$normal+0+0"
bspc rule -a 'Floating'               state=floating center=on
bspc rule -a 'gpclient'               state=floating sticky=on
bspc rule -a 'kscreen_osd_service'    state=floating sticky=on
bspc rule -a 'matplotlib'             state=floating center=on "rectangle=$normal+0+0"
bspc rule -a 'mpv:*:force-focus'      state=floating sticky=on focus=on  border=off
bspc rule -a 'mpv'                    state=floating sticky=on focus=off border=off
bspc rule -a 'pinentry'               state=floating sticky=on

bspc rule -a 'Chromium'                          desktop='1'
bspc rule -a 'Gimp'                              desktop='8' state=floating follow=on
bspc rule -a 'Google-chrome'                     desktop='1'
bspc rule -a 'Main-Tmux'                         desktop='0' follow=on
bspc rule -a 'Meld'                              desktop='7' follow=on
bspc rule -a 'Opera'                             desktop='2'
bspc rule -a 'Qemu-system-x86_64'                desktop='5'
bspc rule -a 'Screenkey'                         manage=off
bspc rule -a 'steam'                             desktop='3'
bspc rule -a 'Steam'                             desktop='3'
bspc rule -a 'Sxiv'                              state=floating center=on "rectangle=$normal+0+0"
bspc rule -a 'VirtualBox Manager'                desktop='4'
bspc rule -a 'VirtualBoxVM'                      desktop='5'
bspc rule -a 'Zathura'                           desktop='6' follow=on
bspc rule -a 'crow-translate'                    state=floating
bspc rule -a 'dolphin'                           desktop='4'
bspc rule -a 'zoom_linux_float_video_window'     state=floating sticky=on
