vim.o.autowrite = true
vim.o.breakindent = true
-- vim.o.clipboard = 'unnamedplus'
vim.o.colorcolumn = '121'
vim.o.complete = vim.o.complete .. ',kspell'
vim.o.completeopt = 'menu,preview,menuone,noinsert,noselect'
vim.o.conceallevel = 3
vim.o.cursorcolumn = true
vim.o.cursorline = true
vim.o.diffopt = vim.o.diffopt .. ',iwhite,vertical,context:3,algorithm:patience,indent-heuristic'
vim.o.expandtab = true
vim.o.fileencodings = 'ucs-bom,utf-8,default,cp1251'
vim.o.fileformats = 'unix,dos,mac'
vim.o.foldcolumn = '2'
vim.o.formatoptions = 'tcqjl'
vim.o.grepformat = '%f:%l:%c:%m'
vim.o.grepprg = 'rg --vimgrep'
vim.o.ignorecase = true
-- vim.o.inccommand = 'split'
vim.o.infercase = true
vim.o.lazyredraw = true
vim.o.list = true
vim.o.listchars = 'tab:  ,trail:␣,extends:>,precedes:<,nbsp:+'
vim.o.matchpairs = vim.o.matchpairs .. ',<:>,«:»'
vim.o.mouse = 'a'
vim.o.number = true
-- vim.o.path='.,'
vim.o.pumheight = 10
vim.o.relativenumber = true
vim.o.scrolloff = 10
vim.o.secure = true
vim.o.shiftround = false
vim.o.shiftwidth = 4
vim.o.shortmess = vim.o.shortmess .. 'c'
vim.o.showbreak = '--->'
vim.o.showmatch = true
vim.o.showmode = false
vim.o.sidescrolloff = 10
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.softtabstop = 4
vim.o.spelllang = 'en,nl,ru'
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.swapfile = false
vim.o.tabstop = 4
vim.o.tags = vim.o.tags .. 'tags;'
vim.o.termguicolors = true
vim.o.textwidth = 120
vim.o.undofile = true
vim.o.virtualedit = 'block'
vim.o.visualbell = true
vim.o.whichwrap = vim.o.whichwrap .. ',<,>,h,l'
vim.o.wildignore = '*.a,*.o,*.obj,.git,*~,*.pyc,*.so,*.swp,*.zip,*.exe,tmp/**,node_modules/**'
vim.o.wildignorecase = true
vim.o.wildoptions = 'pum,tagfile'
vim.o.writebackup = false
vim.go.winborder = 'rounded'

vim.cmd.colorscheme 'molokai-grand'

-- vim.api.nvim_command('filetype indent off')
