#!/usr/bin/env perl

use v5.28;
use warnings;

use File::Basename qw();

my %repo_actions = (
    'main.git' => sub {
        my $topic   = 'DEP';
        my $regex   = qr{ \[ $topic- \d+ \] }xms;
        my $message = <>;
        if ($message !~ $regex) {
            die "[POLICY] Your message is not formatted correctly. Expected [${topic}-xxx] ticket reference\n";
        }
    },
);

my $repo = `git config --get remote.origin.url`;
my $name = File::Basename::basename($repo);

foreach my $match (keys %repo_actions) {
    $repo_actions{$match}->() if $name =~ m/$match/;
}
