#!/usr/bin/env bash

set -Eeuo pipefail

# ABSTRACT: convert provided video files to mp4 container without re-encoding

for file in "$@"; do
	base="${file%.*}"
	ext="${file##*.}"

	[[ "$ext" == "mkv" || "$ext" == "avi" || "$ext" == "webm" ]] || continue

	echo "converting: $file to $base.mp4"
	ffmpeg_args=(
		-loglevel info
		-hide_banner
		-fflags +genpts
		-i "$file"
		-map 0
		-ignore_unknown
		-c:v copy
		-c:a copy
		-sn
		-movflags +faststart
		"${base}.mp4"
	)
	[[ -t 1 ]] || ffmpeg_args+=(-nostats)

	ffmpeg "${ffmpeg_args[@]}"
done
