#!/usr/bin/env bash

set -Euo pipefail

wd="${1/#\~/$HOME}"

ignore_file=$(mktemp -u)

function finish {
	rm -f "$ignore_file"
}
trap finish EXIT

cat ~/.config/fd/ignore >> "$ignore_file"
cat >> "$ignore_file" <<EO_IGNORE
**/.build/
**/.cache/
**/.cargo/
**/.kube/
**/.m2/
**/.snapshots/
**/.ssh/
**/.steam/
**/.testing_binaries/
**/.tidyall.d/
**/.venv/
**/.vim/
**/.zoom/
**/Steam/
**/dosdevices/
**/games/
**/node_modules/
**/share/nvim/
**/share/nvm/
**/share/perlbrew*
**/share/vim/
**/share/virtualenv/
**/slib/
**/venv/
EO_IGNORE

{
	cmd1=(fd -Lapu --type "$2" --ignore-file="$ignore_file" --search-path="$wd")
	cmd2=(find "$wd" -type "$2" -printf '%P\n')
	filt=(grep -v -F '.git/')

	"${cmd1[@]}" \
		|| "${cmd2[@]}" | "${filt[@]}"
} 2>/dev/null
