#!/usr/bin/env bash

set -Euo pipefail

WD="${1/#\~/$HOME}"

IGNORE_FILE=$(mktemp -u)

function finish {
	rm -f "$IGNORE_FILE"
}
trap finish EXIT

cat ~/.config/fd/ignore >> "$IGNORE_FILE"
cat >> "$IGNORE_FILE" <<END
**/.build/
**/.cache/
**/.cargo/
**/.kube/
**/.m2/
**/.snapshots/
**/.ssh/
**/.steam/
**/.testing_binaries/
**/.tidyall.d/
**/.venv/
**/.vim/
**/.zoom/
**/Steam/
**/dosdevices/
**/games/
**/node_modules/
**/share/nvim/
**/share/nvm/
**/share/perlbrew*
**/share/vim/
**/share/virtualenv/
**/slib/
**/venv/
END

{
	CMD1=(fd -Lapu --type "$2" --ignore-file="$IGNORE_FILE" --search-path="$WD")
	CMD2=(find "$WD" -type "$2" -printf '%P\n')
	FILT=(grep -v -F '.git/')

	"${CMD1[@]}" \
		|| "${CMD2[@]}" | "${FILT[@]}"
} 2>/dev/null
