#!/usr/bin/env bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"

ROLE=$1
shift

git-in-repo || {
	echo 'Please run in git repo'
	exit 1
}

cd "$(git root)" &>/dev/null

ROLE="$(realpath --relative-to="$(pwd)/roles" "$ROLE")"

echo "Trying to apply role '$ROLE'"

ANSIBLE_FORCE_COLOR='True'
ANSIBLE_RETRY_FILES_ENABLED='False'
ANSIBLE_ROLES_PATH="$(pwd)/roles:${ANSIBLE_ROLES_PATH:-}"

echo "executing: ansible-playbook $*"
ansible-playbook "$@" /dev/stdin <<END
---
- hosts: [all]
  roles:
    - $ROLE
END
