#!/usr/bin/env bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"

HOST=$1
ROLE=$2
shift
shift

git-in-repo || {
	echo 'Please run in git repo'
	exit 1
}

cd "$(git root)" &>/dev/null

ROLE="$(realpath --relative-to="$(pwd)/roles" "$ROLE")"

echo "Trying to apply role '$ROLE' to host/group '$HOST'..."

ANSIBLE_FORCE_COLOR='True' \
ANSIBLE_RETRY_FILES_ENABLED='False' \
ANSIBLE_ROLES_PATH="$(pwd)/roles:${ANSIBLE_ROLES_PATH:-}" \
ansible-playbook "$@" /dev/stdin <<END
---
- hosts: [$HOST]
  roles:
    - $ROLE
END
