#!/usr/bin/env perl

use v5.36;
use autodie;
use open ':locale';
use utf8;
use warnings 'FATAL' => qw(utf8);
use experimental qw(builtin declared_refs defer for_list refaliasing try);

use Errno        qw(ENOENT);
use Getopt::Long qw(:config auto_version bundling no_ignore_case);
use Pod::Usage;

use Path::Tiny;

use AnyArchive::Create ();

our $VERSION = 1.000;

my %options = ('GZ' => 0);

sub main() {
    GetOptions(
        'gz'     => \$options{'GZ'},
        'help|h' => sub {pod2usage(-verbose => 99, exitval => 0)},
    ) or die "Unable to process command line options\n";

    my @items  = map  {path($_)} @ARGV;
    my @absent = grep {!$_->exists} @items;

    if (@absent) {
        say {*STDERR} 'Not found:';
        say {*STDERR} "\t$_" foreach @absent;
        return ENOENT if @absent;
    }

    my $suffix   = $options{'GZ'} ? '.tgz' : '.tzst';
    my $basename = $items[0]->basename =~ s{(?<!^)[.]\w*$}{}xr;
    my $archive  = Path::Tiny->cwd->child($basename . $suffix);

    $archive->exists
        and die "File already exists: $archive\n";

    try {
        AnyArchive::Create::execute($archive, \@items);
    } catch ($error) {
        warn $error;
        return 1;
    };

    return 0;
}

exit main();

__END__
