#!/usr/bin/env bash

set -Eeuo pipefail

while getopts '' opt; do
	case ${opt} in
		:)
			echo "Option -${OPTARG} requires an argument."
			exit 1
			;;
		?)
			exit 1
			;;
	esac
done

shift $((OPTIND - 1))

yt_dlp_args=(
	--embed-thumbnail
	--format="ba[ext=m4a]"
	--list-formats
	--no-config
	--no-simulate
	-o '%(fulltitle)s {id=%(id)s,up=%(uploader_id)s,ep=%(timestamp)s}.%(ext)s'
)

umask 0002
exec yt-dlp "${yt_dlp_args[@]}" "$@"
