#!/usr/bin/env bash

set -Eo pipefail

UV_PYTHON="${UV_PYTHON:-3.13}"

export UV_PYTHON

uv python install
uv python pin --no-project

uv tool install sqlite-utils --force
uv tool install datasette --force
