#!/usr/bin/env bash

set -Eeuo pipefail

REQUIRED_RUBY_VERSION="${REQUIRED_PERL_VERSION:-3.2}"

# => -------------------------------------------------------------------------------------------------------------- {{{1

rvm install "$REQUIRED_RUBY_VERSION"
# shellcheck disable=SC1010
rvm "$REQUIRED_RUBY_VERSION" do rvm --default use "$REQUIRED_RUBY_VERSION"
# shellcheck disable=SC1010
rvm "$REQUIRED_RUBY_VERSION" do rvm docs generate-ri
