#!/usr/bin/env bash

set -Eo pipefail

# => support synology --------------------------------------------------------------------------------------------- {{{1

[[ -d "/volume1/local/arch/usr" ]] && export OPENSSL_PREFIX="/volume1/local/arch/usr"

# => -------------------------------------------------------------------------------------------------------------- {{{1

PYTHON_REQUIRED_VERSION="3.13.2"
pyenv install -s "$PYTHON_REQUIRED_VERSION"
pyenv global "$PYTHON_REQUIRED_VERSION"
# pip install pynvim
