#!/usr/bin/env bash

set -Eeuo pipefail

if [[ ! -x "$HOME/.local/bin/fnm" ]]; then
	1>&2 echo "> installing fnm to $HOME/.local/bin..."
	url="https://github.com/Schniz/fnm/releases/latest/download/fnm-linux.zip"

	curl -Lsf "$url"                        \
		| zcat      >"$HOME/.local/bin/fnm" \
		&& chmod a+x "$HOME/.local/bin/fnm"
fi

"$HOME/.local/bin/fnm" install lts/jod
"$HOME/.local/bin/fnm" default lts/jod
