#!/usr/bin/env bash

set -Eo pipefail

# => support synology --------------------------------------------------------------------------------------------- {{{1

[[ -d "/volume1/local/arch/usr" ]] && export OPENSSL_PREFIX="/volume1/local/arch/usr"

# => environment -------------------------------------------------------------------------------------------------- {{{1

REQUIRED_PERL_VERSION=5.38.0

NPROC=4
[[ -x "$(command which -- nproc)" ]] && {
	NPROC="$(nproc)"
}

export PERLBREW_ROOT="${PERLBREW_ROOT:-$HOME/perl5/perlbrew}"
export PERLBREW_HOME="${PERLBREW_HOME:-$PERLBREW_ROOT}"
export PATH="$PATH:$PERLBREW_ROOT/bin"

# => check prerequisites ------------------------------------------------------------------------------------------ {{{1

[[ -x "$(command which -- perlbrew 2>/dev/null)" ]] || {
	echo "perlbrew not found, installing it from (https://perlbrew.pl/)"
	curl -sL https://install.perlbrew.pl | bash
}

[[ -f "$PERLBREW_ROOT/etc/bashrc" ]] || {
	perlbrew init
}

# shellcheck disable=SC1091
[[ -n "$PERLBREW_VERSION" ]] || source "$PERLBREW_ROOT/etc/bashrc"

[[ -x "$(command which -- cpanm 2>/dev/null)" ]] || {
	perlbrew install-cpanm || exit 1
}

# => install default perl and library ----------------------------------------------------------------------------- {{{1

PERL_NAME="perl-$REQUIRED_PERL_VERSION"
PERL_NAME_MATCH="\b${PERL_NAME}\b"
[[ $(perlbrew list) =~ $PERL_NAME_MATCH ]] || {
	# https://raw.githubusercontent.com/Perl/perl5/blead/INSTALL
	echo "Installing required perl: $PERL_NAME (nproc: $NPROC)"
	nice perlbrew install -nf -j "$NPROC" "$REQUIRED_PERL_VERSION" --as "$PERL_NAME" \
		-Dinc_version_list=none                                                      \
		-Duserelocatableinc                                                          \
		|| exit 1
	echo
}

LIBRARY_NAME="${PERL_NAME}@default"
LIBRARY_NAME_MATCH="\b${LIBRARY_NAME}\b"
[[ $(perlbrew lib-list) =~ $LIBRARY_NAME_MATCH ]] || {
	echo "Creating Perl local dev library: $LIBRARY_NAME"
	perlbrew lib create "$LIBRARY_NAME" || exit 1
	echo
	echo "Installing required modules"
	perlbrew exec --with "$LIBRARY_NAME" nice cpanm -nq --installdeps "$HOME/.local/lib/perl5"

	rm -f "$PERLBREW_ROOT/init" && perlbrew switch "$LIBRARY_NAME"
}

# => -------------------------------------------------------------------------------------------------------------- {{{1

# perlbrew install perl-5.38.0 -nf -j "$NPROC" --as='bperl5380' -Accflags="-DSILENT_NO_TAINT_SUPPORT" -Duseshrplib -Doptimize="-O3" -UDEBUGGING
# perlbrew install perl-5.38.0 -nf -j "$NPROC" --as='bperl5380-debug' -Accflags="-DSILENT_NO_TAINT_SUPPORT" -Duseshrplib -Doptimize="-Og" -DDEBUGGING --clang
# perlbrew install perl-5.38.0 -nf -j "$NPROC" --as='bperl5380-jemalloc' -Accflags="-DSILENT_NO_TAINT_SUPPORT" -Aldflags="-ljemalloc" -Duseshrplib -Doptimize="-O3" -UDEBUGGING
