#!/usr/bin/env bash

set -Eo pipefail

# => support synology --------------------------------------------------------------------------------------------- {{{1

[[ -d "/volume1/local/arch/usr" ]] && export OPENSSL_PREFIX="/volume1/local/arch/usr"

# => environment -------------------------------------------------------------------------------------------------- {{{1

site_location="$HOME/.local/lib"

# install required perl version and define environment variables
# shellcheck disable=SC1091
source "$site_location/perlbrew-dev.rc"

# install modules into specific library
# shellcheck disable=SC1091
echo "Installing additional required modules from '$site_location/cpanfile'"

{
	nice perlbrew exec --with "$perlbrew_library_name" cpanm -nq --installdeps "$site_location" --with-develop --with-feature=mojo-extras
} 2>&1 | grep -Ev 'LIBARCHIVE[.]xattr[.]com[.](apple|macromates)'

# => switch to the library  --------------------------------------------------------------------------------------- {{{1

echo "Switching to '$perlbrew_library_name'"
(
	# shellcheck disable=SC1091
	source "$PERLBREW_ROOT/etc/bashrc"
	rm -f "$PERLBREW_ROOT/init" && perlbrew switch "$perlbrew_library_name"
)

# => -------------------------------------------------------------------------------------------------------------- {{{1

# perlbrew install perl-5.38.0 -nf -j "$NPROC" --as='bperl5380' -Accflags="-DSILENT_NO_TAINT_SUPPORT" -Duseshrplib -Doptimize="-O3" -UDEBUGGING
# perlbrew install perl-5.38.0 -nf -j "$NPROC" --as='bperl5380-debug' -Accflags="-DSILENT_NO_TAINT_SUPPORT" -Duseshrplib -Doptimize="-Og" -DDEBUGGING --clang
# perlbrew install perl-5.38.0 -nf -j "$NPROC" --as='bperl5380-jemalloc' -Accflags="-DSILENT_NO_TAINT_SUPPORT" -Aldflags="-ljemalloc" -Duseshrplib -Doptimize="-O3" -UDEBUGGING
