#!/usr/bin/env perl

use v5.36;
use autodie;
use open ':locale';
use utf8;
use warnings 'FATAL' => qw(utf8);
use experimental qw(builtin declared_refs defer for_list isa re_strict refaliasing try);

use List::Util qw(any first uniq);

sub main() {
    my $path = $ENV{'HISTFILE'}
        or die "Unable to find histfile\n";

    open(my $fh, '<', $path);
    chomp(my @lines = <$fh>);

    close $fh;

    if (my $line = first {m{\\\z}} @lines) {
        die "Multiline command detected: $line\n";
    }

    my @commands = qw(
        ag
        bat
        bin/git-deploy
        bin/pakket
        brew
        bspc
        cat
        cd
        cget
        chafa
        chmod
        clipcopy
        cp
        dig
        docker
        docker-compose
        du
        echo
        emacs
        emacsclient
        env
        eslint
        exo-open
        extract-here
        fd
        file
        find
        fuse3-7z
        fuse3-p7zip
        fzf-hardlinks
        json2yaml
        sha1sum
        snapper
        spectral
        ssh-copy-id
        stat
        strace
        take
        tar
        telnet
        tldr
        tmux
        touch
        trizen
        umount
        unhmt
        unset
        unzip
        vi
        video-remux
        vifm
        vim
        vimdiff
        wget
        which
        wineboot
        winecfg
        winetricks
        xclip
        xmllint
        xsel
        yaml-sanitize
        yaml2json
        yath
        yc
        you-get
        youtube-dl
        youtube-viewer
    );
    @lines = uniq sort @lines;
    @lines = grep {length > 1} @lines;
    @lines = grep {!m{\A\#}x} @lines;
    @lines = grep {!m{\A[./]+\z}x} @lines;
    @lines = grep {!m{\A-rw-}x} @lines;
    @lines = grep {!m{\Adrwxr}x} @lines;
    @lines = grep {!m{\A[*]{2,}}x} @lines;

    foreach my $command (@commands) {
        @lines = grep {!m{\A\s*$command\s}x} @lines;
    }

    foreach (@lines) {
        say;
    }

    return 0;
}

exit main();

__END__
