#!/usr/bin/env bash

source "$HOME/.local/lib/shell/color.bash"

echo -e "i'am: ${FG[blue]}'$0'${FX[reset]}"
echo "passed args [$#]: ${*@Q}"

if [[ /dev/stdin -ef /dev/null ]]; then
	echo -e "${FG[olive]}STDIN  is a ${FX[reset]}/dev/null"
elif [[ -t 0 ]]; then
	echo -e "${FG[olive]}STDIN  is a ${FX[reset]}tty"
else
	echo -en "${FG[olive]}STDIN  is a ${FX[reset]}"
	file -b /proc/self/fd/0
	# echo -e "${FG[olive]}STDIN data is passed:${FX[reset]}"
	# cat
fi

if [[ /dev/stdout -ef /dev/null ]]; then
	echo -e "${FG[olive]}STDOUT is a ${FX[reset]}/dev/null"
elif [[ -t 1 ]]; then
	echo -e "${FG[olive]}STDOUT is a ${FX[reset]}tty"
else
	echo -en "${FG[olive]}STDOUT is a ${FX[reset]}"
	file -b /proc/self/fd/1
fi

if [[ /dev/stderr -ef /dev/null ]]; then
	echo -e "${FG[olive]}STDERR is a ${FX[reset]}/dev/null"
elif [[ -t 2 ]]; then
	echo -e "${FG[olive]}STDERR is a ${FX[reset]}tty"
else
	echo -en "${FG[olive]}STDERR is a ${FX[reset]}"
	file -b /proc/self/fd/2
fi

for FILE in "$@"; do
	if [[ -r $FILE ]]; then
		echo -e "${FG[olive]}passed file: ${FX[reset]}$(file -i "$FILE")"
	fi
done
