#!/usr/bin/env bash
# url: https://www.youtube.com/watch?v=zB_3FIGRWRU

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"

NOTESDIR="$HOME/.local/var/sync/notes"
DATE="$(date +%F)"
NOTEFILE="$NOTESDIR/note-$DATE.md"

mkdir -p "$NOTESDIR"

[[ -e "$NOTEFILE" ]] || {
	echo "# Notes for $DATE" >> "$NOTEFILE"
}

command vim \
	-c 'norm Go' \
	-c "norm Go## $(date +%H:%M)" \
	-c 'norm G2o' \
	-c 'norm zz' \
	-c 'startinsert' \
	"$NOTEFILE"
