#!/usr/bin/env bash

set -Eeuo pipefail

dir="$XDG_DATA_HOME/db_ui"
file="$dir/connections.json"

mkdir -p "$dir"

[[ -r "$file" ]] || echo '[]' > "$file"

jq --arg name "$1" --arg url "$2" 'map(select(.url != $url)) | [.[], {name: $name, url: $url, scheme: {filetype: "sqlite"}}]' "$file" | sponge "$file"
