#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'f' --longoptions 'fix' -- "$@")
eval set -- "$args"

while ((1)); do
	case "$1" in
		-f | --fix) fix='1'; shift ;;
		--) shift; break ;;
	esac
done

if [[ "${fix:-}" == '1' ]]; then
	if [[ -r "${1:-}" ]]; then
		< "$1" deno fmt --ext=ts --indent-width=4 --line-width=120 --prose-wrap=preserve --single-quote=true - \
			| if [[ -t 1 ]]; then
			tee >(sponge "$1")
		else
			cat
		fi
	else
		cat "$@" | deno fmt --ext=ts --indent-width=4 --line-width=120 --prose-wrap=preserve --single-quote=true -
	fi
else
	# deno check          "$@" 2>&1
	cat "$@" | deno lint  --ext=ts --json -
fi
