#!/usr/bin/env bash

set -Eeuo pipefail

exec 2>/dev/null

args=(-T -M Pod::Man)

if troff=$(perldoc "${args[@]}" -X "$@" \
        || perldoc "${args[@]}" -f "$@" \
        || perldoc "${args[@]}" -v "$@" \
        || perldoc "${args[@]}" -a "$@" \
        || perldoc "${args[@]}" -q "$@"); then
    if [[ -t 1 ]]; then
        MANPAGER="nvim +Man! -c \":nnoremap <buffer> q :quitall<CR>\"" man -l - <<< "$troff"
    else
        MANPAGER="${PAGER:-less}" man -l - <<< "$troff"
    fi
else
    man "$@" || echo "Nothing found for: $*" >&2
fi
