#!/usr/bin/env bash

set -Eeuo pipefail

if [[ -t 1 ]]; then
	export FZF_RELOAD_CMD="$0 | json2tsv | tsv-align"
	fzf_cmd=(
		fzf
		--ansi
		--bind="alt-c:execute-silent(fzf-run-reload -- docker-clean)"
		--bind="alt-g:execute-silent(fzf-run-reload -- docker pull {+-1})"
		--bind="alt-i:execute(docker inspect {-1} | json-pretty -f {-1})"
		--bind="alt-p:toggle-preview,ctrl-alt-w:toggle-preview-wrap,ctrl-s:toggle-sort"
		--bind="alt-r:execute-silent(fzf-run-reload -- docker rmi -f {+1})"
		--bind="alt-s:execute-silent(fzf-run-reload -- docker push {+-1})"
		--bind="ctrl-m:execute(docker inspect {-1} | jq-repl)"
		--bind="ctrl-r:reload($FZF_RELOAD_CMD)"
		--bind="ctrl-y:execute-silent(echo -n {+-1} | clipcopy)"
		--bind="home:top"
		--bind="tab:toggle-out,shift-tab:toggle-in"
		--delimiter="\t"
		--header-lines=1
		--header="C-j/k:move C-m/Enter:jq-repl C-r:reload C-y:yank A-c:clear A-g:pull A-i:inspect A-p:preview A-r:remove A-s:push"
		--multi
		--preview-window="right:60%:border-left:wrap:hidden"
		--preview="docker inspect {-1} | json-pretty -C -f {-1}"
		--prompt="docker images > "
		--reverse
		--scroll-off=4
		--tabstop=4
		--with-nth="..-2"
	)
	eval "$FZF_RELOAD_CMD" | "${fzf_cmd[@]}"
else
	docker images -a --format "{{json . }}" \
		"${OPTIONS[@]}" "$@" 2>/dev/null \
		| jq -nRc '[inputs | fromjson] | sort_by(.repository // .Repository) | map({
			id: (.Id // .ID) | .[0:10],
			# created: (.Created // (.CreatedAt | strptime("%Y-%m-%d %T") | mktime)) | todateiso8601,
			repository: (.repository // .Repository),
			tag: (.tag // .Tag),
			size: .Size,
			use: .Containers,
            path: "\(.repository // .Repository):\(.tag // .Tag)"
	})'
fi
