#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "${1:-}" == "--force" ]]; then
	mapfile -t RUNNING_CONTAINERS < <(command docker ps -q)
	[[ -n "${RUNNING_CONTAINERS[*]}" ]] && {
		echo "Stopping running contaiers: ${#RUNNING_CONTAINERS[@]}"
		command docker kill "${RUNNING_CONTAINERS[@]}"
	}
fi

mapfile -t STOPPED_CONTAINERS < <(command docker ps --filter status=exited -q)
[[ -n "${STOPPED_CONTAINERS[*]}" ]] && {
	echo "Removing stopped contaiers: ${#STOPPED_CONTAINERS[@]}"
	command docker rm "${STOPPED_CONTAINERS[@]}"
}

mapfile -t DANGLING_IMAGES < <(command docker images -f 'dangling=true' -q)
[[ -n "${DANGLING_IMAGES[*]}" ]] && {
	echo "Removing dangling images: ${#DANGLING_IMAGES[@]}"
	command docker rmi -f "${DANGLING_IMAGES[@]}"
}

exit 0
