#!/usr/bin/env bash

set -Eeuo pipefail

TMP_FILE="$(mktemp)"

tmux-pane | trim-trailing-whitespace | perl -gpE 's/\A\R+|\R\K\R+\z//g' > "$TMP_FILE"
tmux new-window -n:history "$(dirname "$0")/vi $TMP_FILE; rm -f $TMP_FILE"
