#!/usr/bin/env bash

set -Eeuo pipefail

TMP_FILE="$(mktemp)"

tmux capture-pane -pJS - | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//' > "$TMP_FILE"
tmux new-window -n:history "nvim $TMP_FILE; rm -f $TMP_FILE"
