#!/usr/bin/env perl

# man: PerlIO

use v5.36;
use autodie;
use open ':std', IN => ':crlf';
use utf8;
use warnings qw(FATAL utf8);

BEGIN {
    # by some kind of a bug open pragma with ':crlf' is not applied to STDIN
    binmode(STDIN, ':crlf');
}

while (<<>>) {
    chomp;
} continue {
    say;
}

__END__
