#!/usr/bin/env perl

# man: PerlIO

use v5.36;
use autodie;
use open ':std', 'OUT' => ':crlf';
use utf8;
use warnings;
use warnings FATAL => qw(utf8);

BEGIN {
    # by some kind of a bug open pragma with ':crlf' is not applied to STDOUT
    binmode(STDOUT, ':raw :crlf');
}

while (<<>>) {
    chomp;
} continue {
    say;
}

__END__
