#!/usr/bin/env bash

set -Eeuo pipefail

CURRENT_SCRIPT="$(basename "$0")"
FETCHER="${CURRENT_SCRIPT#fzf-}"

"$FETCHER" \
	| fzf --multi --bind 'tab:toggle-out,shift-tab:toggle-in' --preview 'git show --color=always HEAD:{}'
