#!/usr/bin/env bash

set -Eeuo pipefail

git-in-repo || exit 95

CURRENT_SCRIPT="$(basename "$0")"

# always include some refs into selection
refs=(
	HEAD
	"$(git bname || true)"
	"$(git main-branch || true)"
)

# filter out empty elements
readarray -t valid_refs < <(echo "${refs[@]}" | xargs -rn1 echo) || true
export FZF_RELOAD_CMD="${CURRENT_SCRIPT#fzf-} ${valid_refs[*]@Q} ${*@Q}"

fzf_args=(
	--prompt="$(git main-project) | log > "
)

eval "$FZF_RELOAD_CMD" | fzf-git-log "${fzf_args[@]}"
