#!/usr/bin/env bash

set -Eeuo pipefail

FZF_CMD=(
	fzf
	--bind='ctrl-d:page-down,ctrl-u:page-up'
	--bind='ctrl-h:preview-up,ctrl-l:preview-down'
	--bind='ctrl-v:toggle-preview,ctrl-w:toggle-preview-wrap,ctrl-s:toggle-sort'
	--bind='ctrl-y:execute-silent(echo -n {2} | perl -nE "print m/\"(.+)\"$/" | clipcopy)'
	--bind="enter:execute(nohup '{2..}' </dev/null &>/tmp/fzf-execute.log & disown; sleep 0.01)+abort"
	--bind='esc:cancel'
	--delimiter='	'
	--no-multi
	--preview-window=right:60%:wrap:hidden
	--preview='echo {2..}'
	--reverse
	--with-nth=1
)

"${FZF_CMD[@]}" "$@"
