#!/usr/bin/env bash

set -Eeuo pipefail

CURRENT_SCRIPT="$(basename "$0")"
FETCH_CMD="${CURRENT_SCRIPT#fzf-}"

"$FETCH_CMD" \
	| fzf --multi --bind 'tab:toggle-out,shift-tab:toggle-in' --preview 'git show --color=always {}'
