#!/usr/bin/env bash

set -Eeuo pipefail

fzf_cmd=(
	fzf
	--ansi
	--bind="enter:execute-silent(set -x; exec 2>>/tmp/$(basename "$0").log; echo \>/dev/null \</dev/null nohup {2..} \& disown\; sleep 0.2 | tee -a /dev/stderr | bash)"
	--bind='ctrl-y:execute-silent(echo -n {2..} | clipcopy)'
	--delimiter=$'\u0009'
	--no-multi
	--preview='echo {2..}'
	--reverse
	--with-nth=1
)

exec "${fzf_cmd[@]}" "$@"
