#!/usr/bin/env bash

set -Eeuo pipefail

CURRENT_SCRIPT="$(basename "$0")"
export FZF_RELOAD_CMD="${CURRENT_SCRIPT#fzf-}"

"$FZF_RELOAD_CMD" \
	| fzf --multi --bind 'tab:toggle-out,shift-tab:toggle-in' --preview ''
