#!/usr/bin/env bash

set -Eeuo pipefail

CURRENT_SCRIPT="$(basename "$0")"
export FZF_RELOAD_CMD="${CURRENT_SCRIPT#fzf-} ${*@Q}"

fzf_cmd=(
	fzf-git-log
	--multi
	--bind="ctrl-m:become(printf '%s\n' {+1})"
	--bind='tab:toggle+down,shift-tab:toggle+up'
)

eval "$FZF_RELOAD_CMD" \
	| "${fzf_cmd[@]}"
