#!/usr/bin/env bash

set -Eeuo pipefail

source "$HOME/.local/lib/shell/fzf.bash"

CURRENT_SCRIPT="$(basename "$0")"
export FZF_RELOAD_CMD="${CURRENT_SCRIPT#fzf-} $*"

fzf_args=(
	"${FZF_GIT_DEFAULT_ARGS[@]}"
	--bind="ctrl-m:become(cat {+f1})"
	--prompt="$(git main-project) | tags > "
)

eval "$FZF_RELOAD_CMD" | fzf-exec-multi "${fzf_args[@]}"
