#!/usr/bin/env bash

set -Eeuo pipefail

args="$(getopt --name="$0" --options='c:' --longoptions='column:' -- "$@")"
eval set -- "$args"

column='2'

# shellcheck disable=SC2078
while [ : ]; do
	case "$1" in
		-c | --column) column="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

fzf_cmd=(
	fzf
	--ansi
	--bind="enter:become(exec 2>>/tmp/$(basename "$0").log; echo \>/dev/null \</dev/null nohup {${column}..} \& disown\; sleep 0.2 | tee -a /dev/stderr | bash)"
	--bind="ctrl-y:execute-silent(echo -n {${column}..} | clipcopy)"
	--delimiter=$'\u0009'
	--no-multi
	--preview="echo {${column}..}"
	--reverse
	--with-nth="..$((column - 1))"
)

exec "${fzf_cmd[@]}" "$@"
