#!/usr/bin/env bash

set -Eeuo pipefail

default_fzf_cmd=(
	fzf
	--ansi
	--bind="alt-p:toggle-preview,ctrl-s:toggle-sort,ctrl-t:toggle-track"
	--bind="ctrl-d:half-page-down,ctrl-u:half-page-up,home:top"
	--bind="ctrl-e:toggle-preview-wrap,ctrl-n:preview-down,ctrl-p:preview-up"
	--bind="ctrl-w:backward-kill-word,esc:cancel"
	--delimiter="\t"
	--no-header
	--header-lines=1
	--listen
	--no-multi
	--reverse
	--scroll-off=4
	--tabstop=4
)

export LC_ALL='en_US.UTF-8'
unicode_bind="alt-b:execute(xdg-open \"https://unicode-table.com/en/\$(echo {} | grep -o '^[[:xdigit:]]\{4,\}')\" &>/dev/null)"
case "$1" in
	emoji)   chosen=$(grep-emoji   | tsv-align | "${default_fzf_cmd[@]}" --prompt="$1 > " --bind="ctrl-m:become(echo -n {2})") ;;
	nerd)    chosen=$(grep-nerd    | tsv-align | "${default_fzf_cmd[@]}" --prompt="$1 > " --bind="ctrl-m:become(echo -n {4})") ;;
	unicode) chosen=$(grep-unicode | tsv-align | "${default_fzf_cmd[@]}" --prompt="$1 > " --bind="ctrl-m:become(echo -n {2})" --bind="$unicode_bind") ;;
	*)       exit ;;
esac

if [[ -n "$chosen" ]]; then
	echo -n "$chosen" | tee >(clipcopy) \
		&& notify-send -i dialog-password "$chosen" 'Copied to the clipboard'
fi
