#!/usr/bin/env bash

set -Eeuo pipefail

FZF_CMD=(
	fzf
	--ansi
	--bind="enter:become(exec 2>>/tmp/$(basename "$0").log; echo \>/dev/null \</dev/null nohup {1} {2} \& disown\; sleep 0.2 | tee -a /dev/stderr | bash)"
	--bind='ctrl-y:execute-silent(echo -n {1} {2} | clipcopy)'
	--delimiter=$'\u0009'
	--no-multi
	--preview='echo {1} {2}'
	--reverse
	--with-nth=3..
)

exec "${FZF_CMD[@]}" "$@"
