#!/usr/bin/env bash

set -Eeuo pipefail

fzf_cmd=(
	fzf
	--ansi
	--bind="enter:execute-silent(set -x; exec 2>>${XDG_RUNTIME_DIR}/$(basename "$0").log; </dev/null &>/dev/null setsid -f -- {2..})"
	--bind="alt-enter:become(set -x; exec 2>>${XDG_RUNTIME_DIR}/$(basename "$0").log; </dev/null &>/dev/null setsid -f -- {2..})"
	--bind='ctrl-y:execute-silent(echo -n {2..} | clipcopy)'
	--delimiter=$'\u0009'
	--no-multi
	--preview='echo {2..}'
	--reverse
	--with-nth=1
)

exec "${fzf_cmd[@]}" "$@"
