#!/bin/bash
# man: git-log

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"

git-in-repo && {
	CMD=(git log
		--color=always
		--abbrev-commit
		--format='%C(yellow)%h %C(bold blue)%an%C(reset) (%C(green)%cr%C(reset)) %s %C(auto)%d'
		--max-count=9999
		"$@"
	)
	"${CMD[@]}"
}
