#!/usr/bin/env zsh

# vim: filetype=sh
# man: zshexpn

set -Euo pipefail

source "$HOME/.local/lib/shell/color.bash"

if [[ "$#" -eq "1" ]] && [[ "$1" =~ \.git/?$ ]]; then
	REPO=$(dirname "$1")

	echo -e "$FG[olive]Fetching ${REPO}$FX[reset]"

	git -C "$REPO" -c color.ui=always -c safe.directory="$REPO" fetch --force --prune --prune-tags \
		&& nice git -C "$REPO" -c safe.directory="$REPO" -c color.ui=always bleach
else
	fd -0uL -E 'bazel-*' -td -tf '\A\.git\z' "${1:-$PWD}" | sort -z | {
		if [[ -n "$(command -v parallel)" ]]; then
			parallel -0j-50% --delay 0.3 "$0" {}
		else
			xargs -0rn1 "$0"
		fi
	}
fi

exit 0
