#!/usr/bin/env bash
# man: git-log

set -Eeuo pipefail

GIT_MAX_COUNT="${GIT_MAX_COUNT:-9999}"

git-in-repo && {
	# make sure all paths can be passed relative to current dir, not relative to the repo root when script called as
	# git alias
	# check how aliases run with a bang: man git-config
	[[ -n "${GIT_PREFIX:-}" ]] && {
		cd -- "$(git root)/$GIT_PREFIX"
		unset GIT_PREFIX
	}

	CMD=(git log
		--color=always
		--abbrev-commit
		--date='format-local:%Y-%m-%d'
		--format='%C(yellow)%h %C(green)%cd %C(cyan)%G?%C(bold blue)%<(24,trunc)%an%C(auto)%d%C(reset) %s'
		--max-count="$GIT_MAX_COUNT"
		--topo-order
		"$@"
	)

	exec "${CMD[@]}"
}
