#!/bin/bash
# man: git-log

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"
MAX=9999

git-in-repo && {
	CMD=(git log
		--color=always
		--abbrev-commit
		--date='format-local:%Y-%m-%d %H:%M'
		--format='%C(yellow)%h %C(bold blue)%an%C(reset) %G?(%C(green)%cd, %cr%C(reset)) %s%C(auto)%d'
		--max-count="$MAX"
		"$@"
	)
	"${CMD[@]}"
}
