#!/usr/bin/env bash
# man: git-log

set -Eeuo pipefail

MAX=9999

git-in-repo && {
	# make sure all paths can be passed relative to current dir, not relative to the repo root when script called as
	# git alias
	# check how aliases run with a bang: man git-config
	[[ -n "$GIT_PREFIX" ]] && cd -- "$GIT_PREFIX"

	CMD=(git log
		--color=always
		--abbrev-commit
		# --date='format-local:%Y-%m-%d %H:%M'
		--format='%C(yellow)%h %C(bold blue)%<(24,trunc)%an%G?%C(auto)%d%C(reset) %s'
		# --format='%C(yellow)%h %C(bold blue)%<(20,trunc)%an%C(reset) %G?(%C(green)%cd, %cr%C(reset)) %s%C(auto)%d'
		--max-count="$MAX"
		--topo-order
		"$@"
	)

	exec "${CMD[@]}"
}
