#!/bin/bash
# man: git-log

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"

git-in-repo && {
	CMD=(git log
		--color=always
		--abbrev-commit
		--date='format-local:%Y-%m-%d %H:%M'
		--format='%C(yellow)%h %C(bold blue)%an%C(reset) (%C(green)%cd, %cr%C(reset)) %s %C(auto)%d%G?'
		--max-count=9999
		"$@"
	)
	"${CMD[@]}"
}
