#!/usr/bin/env zsh

# man: zshexpn

set -Euo pipefail

setopt globdots

CWD=${1:-$(pwd)}
GIT_DIRS=("$CWD"/**/.git)

for DIR in "$CWD"/*(@N); do
	GIT_DIR="$DIR/.git"

	[[ -d "$GIT_DIR" ]] && GIT_DIRS+=("$GIT_DIR")
done

function process_git_dir() {
	REPO=$(dirname "$1")
	shift

	echo -e '\033[0;33m'"Updating $REPO"'\033[0m'

	git -C "$REPO" fetch --all -p \
	&& git -C "$REPO" pull
}

for GIT_DIR in "${(ou)GIT_DIRS[@]}"; do
	process_git_dir "$GIT_DIR"
done
