#!/bin/bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"

git-in-repo && {
	git checkout --orphan empty-initial-commit
	git rm -rf .
	git commit --allow-empty -m 'Empty initial commit'
	git checkout master
	git rebase empty-initial-commit
	git branch -d empty-initial-commit
}
