#!/usr/bin/env bash

set -Eeuo pipefail

source "$(dirname "$0")/git-gl-common"

# HEAD=$(&>/dev/null git fetch --no-tags --porcelain "$REMOTE" HEAD)
&>/dev/null git fetch --no-tags --porcelain "$REMOTE" "merge-requests/$1/head"

git diff "...FETCH_HEAD"
