#!/usr/bin/env bash

set -Eeuo pipefail

source "$(dirname "$0")/git-gl-common"

&>/dev/null git fetch "$REMOTE"
&>/dev/null git fetch "$REMOTE" "merge-requests/$1/head"

git diff "$REMOTE/HEAD...FETCH_HEAD"
