#!/usr/bin/env bash

# ABSTRACT: simple git credentials helper for `pass` password manager

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'p:' --longoptions 'path:' -- "$@")
eval set -- "$args"

while ((1)); do
	case "$1" in
		-p | --path) pth="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

# only get command is supported
[[ "${1:-}" == 'get' ]] || exit

# expose input as environment
# source <(cat) approach is not working because it fails if space is in values
while read -r line; do
	IFS='=' read -r key value <<< "$line"
	eval "$key='$value'"
done

if [[ -z "${pth:-}" ]] && [[ "${protocol:-}" != 'https' || -z "${host:-}" || -z "${username:=$USER}" ]]; then
	echo "continue=1"
	exit 0
fi

if data="$(pass show "${pth:-"token/$protocol/$host/$username"}" 2>/dev/null)"; then
	if [[ "$data" =~ password= ]]; then
		echo "$data"
	else
		echo "password=$data"
	fi
	[[ "$data" =~ username= ]] || echo "username=$username"
	echo "protocol=$protocol"
	echo "host=$host"
	exit 0
fi

echo "continue=1"
