#!/bin/bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"

git-in-repo && {
	MAIN_BRANCH="$(git gmb)"
	git checkout --orphan new-root
	git rm -rf .
	git commit --allow-empty -m 'init: empty commit'
	git rebase --committer-date-is-author-date -i new-root "$MAIN_BRANCH"
	git branch -d new-root
}
