#!/usr/bin/env zsh

# man: zshexpn

set -Euo pipefail

if [[ "$#" -eq "1" ]] && [[ "$1" =~ \.git/?$ ]]; then
	if [[ "$1" =~ ^\.git/?$ ]]; then
		REPO=$(dirname "$1")

	echo -n "$(tput setaf 3)"
	echo "Gc aggressive  $REPO"
	echo -n "$(tput sgr0)"

	git -C "$REPO" fetch \
		&& nice git -C "$REPO" bleach
	nice git -C "$REPO" reflog expire --all --expire=now \
		&& nice git -C "$REPO" gc --prune=now --aggressive
else
	fd -HIL -td -tf -0 '\A.git\z' "${1:-$PWD}" | {
		if [[ -n "$(command -v parallel)" ]]; then
			parallel -k -j-2 --delay 0.3 -0 "$0" {}
		else
			xargs -0 --max-args=1 --no-run-if-empty "$0"
		fi
	}
fi
