#!/usr/bin/env bash

set -Eeuo pipefail

# ABSTRACT: simple git credentials helper just for echoing input

# only get command is supported
[[ "${1:-}" == 'get' ]] || exit

payload="$(</dev/stdin)"

cat <<< "$payload"
[[ "$payload" =~ username= ]] || echo username=
[[ "$payload" =~ password= ]] || echo password=
