#!/usr/bin/env bash

set -Eeuo pipefail

args="$(getopt --name="$0" --options 'h:p:' --longoptions 'host:,project:' -- "$@")"
eval set -- "$args"

# shellcheck disable=SC2078
while [ : ]; do
	case "$1" in
		-h | --host) HOST="$2"; shift 2 ;;
		-p | --project) PROJECT="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

# shellcheck disable=SC1090
source "$(realpath -Ls "$(dirname "$0")/../lib/shell/data-processing.bash")"
# shellcheck disable=SC1090
source "$(realpath -Ls "$(dirname "$0")/../lib/shell/gitlab.bash")"

# https://docs.gitlab.com/ee/api/branches.html#delete-repository-branch

if [[ -x "$(command -v xhs)" ]]; then
	http_fetch_command=(
		xhs
		DELETE
		"$HOST/$API/projects/$(url_encode "$PROJECT")/repository/branches/{}"
		"${COMMON_XH_OPTIONS[@]}"
	)
else
	http_fetch_command=(
		curl
		-X DELETE
		"https://${HOST}/$API/projects/$(url_encode "$PROJECT")/repository/branches/{}"
		"${COMMON_CURL_OPTIONS[@]}"
	)
fi

printf '%s\n' "$@" | jq -Rr @uri | xargs --no-run-if-empty -I{} -P "$JOBS" "${http_fetch_command[@]}"
