#!/usr/bin/env bash

set -Eeuo pipefail

args="$(getopt --name="$0" --options 'h:p:' --longoptions 'host:,project:' -- "$@")"
eval set -- "$args"

# shellcheck disable=SC2078
while [ : ]; do
	case "$1" in
		-h | --host) HOST="$2"; shift 2 ;;
		-p | --project) PROJECT="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

source "$HOME/.local/lib/shell/gitlab.bash"

# https://docs.gitlab.com/ee/api/branches.html#delete-repository-branch

http_fetch_command=(
	xhs
	DELETE
	"$HOST/$API/projects/$(url_encode "$PROJECT")/repository/branches/{}"
	"${COMMON_XH_OPTIONS[@]}"
)

&>/dev/stderr echo "Deleting branches: $*"
printf '%s\n' "$@" | jq -Rr @uri | xargs --no-run-if-empty -I{} -P "$JOBS" "${http_fetch_command[@]}"
