#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'uh:p:' --longoptions 'unapprove,host:,project:' -- "$@")
eval set -- "$args"

action="approve"

while ((1)); do
	case "$1" in
		-h | --host) GL_HOST="$2"; shift 2 ;;
		-p | --project) GL_PROJECT="$2"; shift 2 ;;
		-u | --unapprove) action="unapprove"; shift ;;
		--) shift; break ;;
	esac
done

source "$HOME/.local/lib/shell/gitlab.bash"
gl-redefine-vars
export -f gl-mr-approve

>&2 echo "Approving MRs: $*"
printf '%s\n' "$@" | jq -Rr @uri | xargs -rI% bash -c "echo Approving %; gl-mr-approve '$GL_PROJECT' '%' '$action'"
