#!/usr/bin/env bash

set -Eeuo pipefail

args="$(getopt --name="$0" --options 'h:p:' --longoptions 'host:,project:' -- "$@")"
eval set -- "$args"

# shellcheck disable=SC2078
while [ : ]; do
	case "$1" in
		-h | --host) HOST="$2"; shift 2 ;;
		-p | --project) PROJECT="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

# shellcheck disable=SC1090
source "$(realpath -Ls "$(dirname "$0")/../lib/shell/data-processing.bash")"
# shellcheck disable=SC1090
source "$(realpath -Ls "$(dirname "$0")/../lib/shell/gitlab.bash")"

# https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr

if [[ -x "$(command -v xhs)" ]]; then
	http_fetch_command=(
		xhs
		"${HOST}/$API/projects/$(url_encode "$PROJECT")/merge_requests/$1"
		"${COMMON_XH_OPTIONS[@]}"
	)
else
	http_fetch_command=(
		curl
		"https://${HOST}/$API/projects/$(url_encode "$PROJECT")/merge_requests/$1"
		"${COMMON_CURL_OPTIONS[@]}"
	)
fi

exec "${http_fetch_command[@]}"
