#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'ah:p:s:' --longoptions 'approve,host:,project:,sleep:' -- "$@")
eval set -- "$args"

sleep_sec=60

while ((1)); do
	case "$1" in
		-a | --approve) approve="1"; shift ;;
		-h | --host) export GL_HOST="$2"; shift 2 ;;
		-p | --project) GL_PROJECT="$2"; shift 2 ;;
		-s | --sleep) sleep_sec="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

source "$HOME/.local/lib/shell/gitlab.bash"
gl-redefine-vars
export -f gl-mr-approve
export -f gl-mr-merge

>&2 echo "Merging MRs (sleep $sleep_sec): $*"

# flag that tail is being executed and sleep is required
flag="$(mktemp --tmpdir="${XDG_RUNTIME_DIR:-/tmp}")"
trap 'rm -f "$flag"' EXIT

printf '%s\n' "$@" | jq -Rr @uri \
	| xargs -rI% bash -c "
		[[ '${approve:-}' == '1' ]] && gl-mr-approve '$GL_PROJECT' '%' 'approve'
		[[ -s $flag ]] && sleep $sleep_sec;
		gl-mr-merge '$GL_PROJECT' '%' && echo '%' >> '$flag'
"
