#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'uh:p:' --longoptions 'unapprove,host:,project:' -- "$@")
eval set -- "$args"

action="approve"

while ((1)); do
	case "$1" in
		-h | --host) GL_HOST="$2"; shift 2 ;;
		-p | --project) GL_PROJECT="$2"; shift 2 ;;
		-u | --unapprove) action="unapprove"; shift ;;
		--) shift; break ;;
	esac
done

source "$HOME/.local/lib/shell/gitlab.bash"
gl-redefine-vars
export -f gl-define-xh-options
export -f gl-mr-approve
export -f url_encode

&>/dev/stderr echo "Approving MRs: $*"
printf '%s\n' "$@" | jq -Rr @uri | xargs --no-run-if-empty -I% -P "$GL_JOBS" bash -c "gl-mr-approve '$GL_PROJECT' '%' '$action'"
