#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'ah:p:s:' --longoptions 'approve,host:,project:,sleep:' -- "$@")
eval set -- "$args"

sleep_sec=10

while ((1)); do
	case "$1" in
		-a | --approve) approve="1"; shift ;;
		-h | --host) export GL_HOST="$2"; shift 2 ;;
		-p | --project) GL_PROJECT="$2"; shift 2 ;;
		-s | --sleep) sleep_sec="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

source "$HOME/.local/lib/shell/gitlab.bash"
gl-redefine-vars
export -f gl-define-xh-options
export -f gl-mr-approve
export -f gl-mr-merge
export -f url_encode

&>/dev/stderr echo "Merging MRs (sleep $sleep_sec): $*"

printf '%s\n' "$@" | jq -Rr @uri | xargs -rI% \
	bash -c "if [[ '${approve:-}' == '1' ]]; then gl-mr-approve '$GL_PROJECT' '%' 'approve'; fi; gl-mr-merge '$GL_PROJECT' '%' && sleep $sleep_sec"
