#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'h:p:m:s:t:' --longoptions 'host:,project:,message:,source:,target:' -- "$@")
eval set -- "$args"

while ((1)); do
	case "$1" in
		-h | --host) GL_HOST="$2"; shift 2 ;;
		-p | --project) GL_PROJECT="$2"; shift 2 ;;
		-m | --message) message="$2"; shift 2 ;;
		-s | --source) source="$2"; shift 2 ;;
		-t | --target) target="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

[[ -z "${message:-}" ]] && { echo "message is required"; exit 1; }
[[ -z "${source:-}" ]]  && { echo "source is required"; exit 1; }
[[ -z "${target:-}" ]]  && { echo "target is required"; exit 1; }

source "$HOME/.local/lib/shell/gitlab.bash"
gl-redefine-vars

gl-mr-create "$GL_PROJECT" "$message" "$source" "$target"
