#!/usr/bin/env bash

set -Eeuo pipefail

[[ -x "$(command -v jq)" ]] || {
	echo "jq is not installed. Please install from 'https://jqlang.github.io/jq/download/'"
	exit 1
}

if [[ -t 1 ]]; then
	[[ -x "$(command -v fzf)" ]] || {
		echo "fzf is not installed. Please install from 'https://github.com/junegunn/fzf#installation'"
		exit 1
	}

	query='?per_page=100'
	since='2 month ago'
	state='opened'
	table='1'
	wip='0'
else
	query='?per_page=100'
	since='3 month ago'
	state='all'
	table='0'
	wip='0'
fi

args="$(getopt --name="$0" --options 'twa:h:p:s:' --longoptions 'table,wip,author:,host:,project:,since:,state:' -- "$@")"
eval set -- "$args"
args=("$@")

# shellcheck disable=SC2078
while [ : ]; do
	case "$1" in
		-a | --author) query+="&author_username=$2"; shift 2 ;;
		-h | --host) HOST="$2"; shift 2 ;;
		-p | --project) PROJECT="$2"; shift 2 ;;
		--since) since="$2"; shift 2 ;;
		-s | --state) state="$2"; shift 2 ;;
		-t | --table) table='1'; shift ;;
		-w | --wip) wip='1'; shift ;;
		--) shift; break ;;
	esac
done

# shellcheck disable=SC1090
source "$(realpath -Ls "$(dirname "$0")/../lib/shell/data-processing.bash")"
# shellcheck disable=SC1090
source "$(realpath -Ls "$(dirname "$0")/../lib/shell/gitlab.bash")"

if [[ -t 1 ]]; then
	if [[ -x "$(command -v json-pretty)" ]]; then
		prettify_json=(json-pretty --no-filename --color=always)
	else
		prettify_json=(jq -SC '|' less)
	fi

	if [[ -x "$(command -v delta)" ]]; then
		prettify_diff=('|' delta --paging=always)
	else
		prettify_diff=()
	fi

	fetcher=(
		"$0"
		--since "$since"
		--state "$state"
		--table
		"${args[@]}"
	)

	fzf_cmd=(
		fzf
		--ansi
		--bind="alt-a:reload-sync(gl-mr-approve -h '$HOST' -p '$PROJECT' {+1} &>/dev/null; ${fetcher[*]@Q})"
		--bind="alt-b:execute-silent(python3 -mwebbrowser {-1})"
		--bind="alt-m:reload-sync(gl-mr-merge -h '$HOST' -p '$PROJECT' {+1} &>/dev/null; ${fetcher[*]@Q})"
		--bind="alt-p:toggle-preview,ctrl-alt-w:toggle-preview-wrap,ctrl-s:toggle-sort"
		--bind="alt-s:execute(gl-mr {1} | ${prettify_json[*]})"
		--bind="alt-r:execute-silent(gl-mr-approve -h '$HOST' -p '$PROJECT' {+1} -u)+reload-sync(${fetcher[*]@Q})"
		--bind="alt-q:execute({ echo \"Approved by:\"; echo; gl-approve-list -t -h '$HOST' -p '$PROJECT' {1}; } | less)"
		--bind="ctrl-m:execute(gl-mr-diff {1} ${prettify_diff[*]})"
		--bind="ctrl-r:reload-sync(${fetcher[*]@Q})"
		--bind="ctrl-x:become(echo -n {+1} | tee >(clipcopy); echo)"
		--bind="ctrl-y:execute-silent(echo -n {} | clipcopy)"
		--bind="esc:cancel"
		--bind="home:top"
		--bind="tab:toggle+down,shift-tab:toggle+up"
		--delimiter="\t"
		--header-lines=1
		--header="A-a:approve A-b:browse A-p:preview A-q:approvals A-m:merge A-s:payload A-r:revoke C-r:reload C-x:dump C-y:yank Enter:diff"
		--multi
		# --no-sort
		--preview-window=right:60%:border-left:wrap:hidden
		--preview="gl-mr-diff {1} ${prettify_diff[*]:0:2}"
		--prompt="$PROJECT > "
		--reverse
		# --scheme=history
		--scroll-off=4
		--tabstop=4
		--track
	)

	"${fetcher[@]}" | "${fzf_cmd[@]}"
else
	[[ "$wip" == '0' ]] && query+='&wip=no'
	[[ -n "$state" ]]   && query+="&state=$state"
	if [[ -n "${since:-}" ]]; then
		# created_after=$(date --rfc-3339=seconds --date="$(date +%Y-%m-01) -1 month")
		created_after=$(date --rfc-3339=seconds --date="$since")
		query+="&created_after=$(url_encode "$created_after")"
	fi

	# https://docs.gitlab.com/ee/api/merge_requests.html#list-project-merge-requests

	if [[ -x "$(command -v xhs)" ]]; then
		http_fetch_command=(
			xhs
			"${HOST}/$API/projects/$(url_encode "$PROJECT")/merge_requests${query}"
			"${COMMON_XH_OPTIONS[@]}"
		)
	else
		http_fetch_command=(
			curl
			"https://${HOST}/$API/projects/$(url_encode "$PROJECT")/merge_requests${query}"
			"${COMMON_CURL_OPTIONS[@]}"
		)
	fi

	if [[ "$table" == "1" ]]; then
		jq_fields=(
			"id;$(tput setaf 3)\(.iid)$(tput sgr0)"
			"created;$(tput setaf 2)\(.updated_at[0:10])$(tput sgr0)"
			'wip;\(if .work_in_progress then 1 else 0 end)'
			'state;\(.state)'
			# 'project_id;\(.project_id)'
			"name;$(tput setaf 12)\(.author.name)$(tput sgr0)"
			"author;$(tput setaf 13)\(.author.username)$(tput sgr0)"
			# "project;$(tput setaf 6)$PROJECT$(tput sgr0)"
			"branch;$(tput setaf 7)\(.source_branch)$(tput sgr0)"
			'title;\(.title)'
			"url;$(tput setaf 14)\(.web_url)$(tput sgr0)"
		)

		"${http_fetch_command[@]}" | json-array-to-tsv "sort_by(.iid) | reverse" "${jq_fields[@]}"
	else
		"${http_fetch_command[@]}"
	fi
fi
