#!/usr/bin/env bash

set -Eeuo pipefail

args="$(getopt --name="$0" --options 'uh:p:' --longoptions 'unapprove,host:,project:' -- "$@")"
eval set -- "$args"

action="approve"

# shellcheck disable=SC2078
while [ : ]; do
	case "$1" in
		-h | --host) HOST="$2"; shift 2 ;;
		-p | --project) PROJECT="$2"; shift 2 ;;
		-u | --unapprove) action="unapprove"; shift ;;
		--) shift; break ;;
	esac
done

source "$HOME/.local/lib/shell/gitlab.bash"

# https://docs.gitlab.com/ee/api/merge_request_approvals.html#approve-merge-request

http_fetch_command=(
	xhs
	POST
	"$HOST/$API/projects/$(url_encode "$PROJECT")/merge_requests/{}/$action"
	"${COMMON_XH_OPTIONS[@]}"
)

printf '%s\n' "$@" | jq -Rr @uri | xargs --no-run-if-empty -I{} -P "$JOBS" "${http_fetch_command[@]}"
