#!/usr/bin/env -S perl -CALDS

use v5.36;

use English qw(-no_match_vars);

my $match = qr{[#]\s (?<emoji>\S+) \sE\d+ [.] \d+\s (?<name>.*)}x;

push(@ARGV, '/usr/share/unicode/emoji/emoji-test.txt') if @ARGV == 0;

say 'name', "\t", 'emoji';
while (defined(my $line = <<>>)) {
    chomp($line);
    length($line) && substr($line, 0, 1) ne '#'
        or next;

    if ($line =~ $match) {
        say $LAST_PAREN_MATCH{'name'}, "\t", $LAST_PAREN_MATCH{'emoji'};
    }
}
