#!/usr/bin/env bash

set -Eeuo pipefail

FILE="$HOME/.config/zsh-history"

TEMP_FILE=$(mktemp)

function finish {
	rm -f "$TEMP_FILE"
}
trap finish EXIT


REGEX="$(tee "$TEMP_FILE" | sk --reverse --regex --print-query | head -1)"

if [[ -n "$REGEX" ]]; then
	echo "Pruning history for regex: '$REGEX'"
	cp -f "$FILE" "$FILE.prune.bak"

	echo "Lines before: $(wc -l < "$FILE")"
	grep -v -P "$REGEX" "$TEMP_FILE" > "$TEMP_FILE.2"
	echo "Lines after: $(wc -l < "$TEMP_FILE.2")"
	mv -f "$TEMP_FILE.2" "$FILE"
fi
