#!/usr/bin/env perl

use v5.34;
use autodie;
use open ':locale';
use utf8;
use warnings;
use warnings FATAL => qw(utf8);
use experimental qw(declared_refs refaliasing signatures try);

use Digest::SHA qw(sha256_hex);
use Encode qw(decode);
use Getopt::Long qw(:config auto_version bundling no_ignore_case);
use Pod::Usage;

use File::Map qw(map_file);
use Log::Any qw($log);
use Log::Any::Adapter ('Stderr', log_level => 'info');
use Path::Tiny;

our $VERSION = 2.04;

use constant {
    'PARTIAL_CHECKSUM_SIZE' => 1 * 1_024 * 1_024,
    'FS_ENCODING'           => 'UTF-8',
};

my %options = (
    'APPLY'    => 0,
    'FOLLOW'   => 0,
    'MIN_SIZE' => 1_024,
    'RECURSE'  => 0,
    'VERBOSE'  => 0,
);

sub main {
    GetOptions(
        'apply|a'    => \$options{'APPLY'},
        'help|h'     => sub {pod2usage('-verbose' => 99, 'exitval' => 0)},
        'min|m=i'    => \$options{'MIN_SIZE'},
        'follow|f'   => \$options{'FOLLOW'},
        'recurse|r'  => \$options{'RECURSE'},
        'verbose|v+' => \$options{'VERBOSE'},
    ) or die "Unable to process command line options\n";

    $log->{'adapter'}{'log_level'} += $options{'VERBOSE'};

    @ARGV
        or push (@ARGV, '.');

### Regroup files by dev + size
    my \%by_dev_size = _regroup_arrays(
        gather_files(),
        'key' => sub ($, $value) {
            return sprintf ('d(%d)s(%d)', $value->{'stat'}->dev, $value->{'stat'}->size);
        },
    );

### Prepare order by dev and file size
    my @order = sort { ## no critic [BuiltinFunctions::RequireSimpleSortBlock]
        my ($stat_a, $stat_b) = ($by_dev_size{$a}[0]{'stat'}, $by_dev_size{$b}[0]{'stat'});
        $stat_a->dev <=> $stat_b->dev or $stat_a->size <=> $stat_b->size
    } keys %by_dev_size;

### Process every size group
    my $counter = 0;
    my $amount  = scalar @order;
    foreach my $key (@order) {
        $counter++;
        my \@items = $by_dev_size{$key};
        my $size = $items[0]{'stat'}->size;

        $log->debugf('Processing bucket    (%d/%d/%d) %s', $counter, $amount, scalar @items, $key);

        my $group = {%by_dev_size{$key}};
        if (PARTIAL_CHECKSUM_SIZE() < $size) {
            $group = _regroup_arrays(
                $group,
                'selector' => sub ($,    $value) {$value->@* > 1},
                'key'      => sub ($key, $value) {
                    $value->{'partial_checksum'} //= do {
                        map_file(my $map, $value->{'paths'}[0]);
                        sha256_hex(substr ($map, 0, PARTIAL_CHECKSUM_SIZE()));
                    };
                    return sprintf ('%sp(%s)', $key, $value->{'partial_checksum'});
                },
            );
        }

        $group = _regroup_arrays(
            $group,
            'selector' => sub ($,    $value) {$value->@* > 1},
            'key'      => sub ($key, $value) {
                $value->{'checksum'} //= do {
                    map_file(my $map, $value->{'paths'}[0]);
                    sha256_hex($map);
                };
                return sprintf ('%sc(%s)', $key, $value->{'checksum'});
            },
        );

        foreach my $key (keys $group->%*) {
            $log->tracef('Checksum subbucket  (%d/%d/%d) %s', $counter, $amount, scalar @items, $key);
            _process_identical_checksums($key, $group->{$key}->@*);
        }
    }

    return 0;
}

### gather files and group them by dev && inode
sub gather_files() {
    $log->debug('Gathering files');

    my %by_dev_ino;
    my $files_amount = 0;
    foreach my $folder (@ARGV) {
        path($folder)->visit(
            sub ($path, @) {

                $path->is_file && !-l $path
                    or return;

                my $stat = $path->stat;
                _is_valid_file($path, $stat)
                    or return;

                ++$files_amount;
                my \%it = $by_dev_ino{sprintf ('d(%d)i(%d)', $stat->dev, $stat->ino)}[0] //= {'stat' => $stat};
                push ($it{'paths'}->@*, decode('UTF-8', $path->stringify, Encode::FB_CROAK));
            },
            {
                'follow_symlinks' => $options{'FOLLOW'},
                'recurse'         => $options{'RECURSE'},
            },
        );
    }
    $log->debug('Gathering files finished: ', $files_amount);

    return \%by_dev_ino;
}

sub _is_valid_file ($path, $stat) {
    return $stat->size >= $options{'MIN_SIZE'};
}

sub _regroup_arrays ($current, %params) {
    my %result;

    while (my ($key, $items) = each ($current->%*)) {
        next if $params{'selector'} && !$params{'selector'}->($key, $items);

        push ($result{$params{'key'}->($key, $_)}->@*, $_) foreach $items->@*;
    }

    return \%result;
}

sub _process_identical_checksums ($checksum, @inodes) {
    @inodes > 1 or do {
        $log->debug('Skipping subbucket: ', $checksum);
        return;
    };

    @inodes = sort { ## no critic [BuiltinFunctions::ProhibitReverseSortBlock]
               $a->{'stat'}->mtime <=> $b->{'stat'}->mtime
            or $b->{'paths'}->@*   <=> $a->{'paths'}->@*
    } @inodes;

    my $main_inode = shift @inodes;
    my $main_path  = $main_inode->{'paths'}[0];
    foreach my $inode (@inodes) {
        _do_hardlink($main_path, path($_)) foreach $inode->{'paths'}->@*;
    }

    return;
}

sub _do_hardlink ($path, $new_path) {
    my $message = join (' <- ', $path, $new_path);
    $log->info('Hardlinking: ', $message);

    if ($options{'APPLY'}) {
        my $backup = path($new_path . '.hardlinker');

        try {
            $new_path->move($backup);
            link ($path, $new_path);
            $backup->remove;
        } catch ($error) {
            croak("Unable to hardlink files $message: $error");
        };
    }

    return;
}

exit main();

__END__

=encoding UTF-8

=head1 NAME

hardlinker

=head1 DESCRIPTION

Detect and hardlink all identical files in given folders.

=head1 SYNOPSIS

hardlinker [options] [dir ...]

=head1 OPTIONS

=over 4

=item B<--apply>

Do real changes on file system

=item B<--recurse>

Process subfolders

=item B<--verbose>

Increase verbosity

=item B<--min>

Minimum size of file to process (default: 1024 bytes)

=back

=cut
