#!/usr/bin/env perl

use v5.36;
use autodie;
use open ':locale';
use utf8;
use warnings     qw(FATAL utf8);
use experimental qw(builtin declared_refs defer for_list refaliasing try);

use Encode qw();

use Path::Tiny qw(path);

our $VERSION = 1;

sub main() {
    @ARGV
        or push(@ARGV, '.');

    foreach my $dir (@ARGV) {
        path($dir)->visit(
            sub ($path, $) {
                $path->is_file && !-l $path
                    or return;

                my $stat = $path->stat;
                say Encode::decode('UTF-8', $path->stringify, Encode::FB_CROAK) if $stat->nlink > 1;
            },
            {
                'recurse'         => 1,
                'follow_symlinks' => 0,
            },
        );
    }

    return 0;
}

exit main();

__END__
