#!/usr/bin/env bash
# shellcheck disable=SC1090
set -Eeuo pipefail

VERB_URL=()
if [[ -n "${VERB:-}" ]]; then
	VERB_URL+=("$VERB")
fi

if [[ $# -eq 0 ]]; then
	if [[ -z "${URI:-}" ]]; then
		echo 'Not enough arguments' >/dev/stderr
		exit 1
	else
		VERB_URL+=("$URI")
	fi
else
	FILE="${1:-}"

	if [[ -n "$FILE" && -r "$FILE" ]]; then
		shift
		source "$FILE" && {
			readarray -t VARS < <(sed -nE '/^[[:space:]]*#/d; s/^[[:space:]]*([[:alpha:]_][[:alnum:]_]+?)=.+/\1/p' "$FILE") || true
			export "${VARS[@]}"
		}
		if [[ -n "${VERB:-}" ]]; then
			VERB_URL+=("$VERB")
		fi

		if [[ -z "${HOST:-}" ]]; then
			if [[ -z "${URI:-}" ]]; then
				VERB_URL+=("${HOST:-:80}${URI:-/}")
			else
				VERB_URL+=("$URI")
			fi
		else
			VERB_URL+=("${HOST}${URI:-/}")
		fi
	fi
fi

if [[ "$0" =~ xh$ ]]; then
	XH=(xh)

	if [[ "${VERB_URL[*]}" =~ 'prod' ]]; then
		opts+=(
			--https
		)
	fi
else
	XH=(xhs)
fi

if [[ -t 1 ]]; then
	opts+=(
		--all
		--pretty=all
		--print=HBhbm
	)
fi

if [[ -n "${BODY:-}" ]]; then
	OPTS+=(
		--raw="$BODY"
	)
fi

echo -n "portable: " > /dev/stderr
"${XH[@]}" "${VERB_URL[@]}" "$@" "${OPTS[@]}" --curl | tee /dev/stderr | primarycopy
echo > /dev/stderr

cmd=("${XH[@]}" "${VERB_URL[@]}" "$@" "${opts[@]}" "${OPTS[@]}")
cmd_str="${cmd[0]}$(printf ' %q' "${cmd[@]:1}")"
echo -n "executing: " > /dev/stderr
echo -e "$cmd_str" > /dev/stderr
echo > /dev/stderr

"${cmd[@]}"
