#!/usr/bin/env bash
# shellcheck disable=SC1090
set -Eeuo pipefail

args="$(getopt --name="$0" --options 'j:r' --longoptions 'jq:,repl' -- "$@")"
eval set -- "$args"

# shellcheck disable=SC2078
while [ : ]; do
	case "$1" in
		-r | --repl) REPL='1'; shift ;;
		-j | --jq) JQ="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done


VERB_URL=()
if [[ -n "${VERB:-}" ]]; then
	VERB_URL+=("$VERB")
fi

if [[ $# -eq 0 ]]; then
	if [[ -z "${URI:-}" ]]; then
		echo 'Not enough arguments' >/dev/stderr
		exit 1
	else
		VERB_URL+=("$URI")
	fi
else
	FILE="${1:-}"

	if [[ -n "$FILE" && -r "$FILE" ]]; then
		shift
		source "$FILE" && {
			readarray -t VARS < <(sed -nE '/^[[:space:]]*#/d; s/^[[:space:]]*([[:alpha:]_][[:alnum:]_]+?)=.+/\1/p' "$FILE") || true
			export "${VARS[@]}"
		}
		if [[ -n "${VERB:-}" ]]; then
			VERB_URL+=("$VERB")
		fi

		if [[ -z "${HOST:-}" ]]; then
			if [[ -z "${URI:-}" ]]; then
				VERB_URL+=("${HOST:-:80}${URI:-/}")
			else
				VERB_URL+=("$URI")
			fi
		else
			VERB_URL+=("${HOST}${URI:-/}")
		fi
	fi
fi

if [[ "$0" =~ xh$ ]]; then
	XH=(xh)

	if [[ "${VERB_URL[*]}" =~ 'prod' || "${VERB_URL[*]}" =~ 'dqs' ]]; then
		opts+=(
			--https
		)
	fi
else
	XH=(xhs)
fi

if [[ -t 1 && -z "${JQ:-}" && -z "${REPL:-}" ]]; then
	opts+=(
		--all
		--pretty=all
		--print=HBhbm
	)
fi

if [[ -n "${BODY:-}" ]]; then
	OPTS+=(
		--raw="$BODY"
	)
fi

if [[ -n "${REPL:-}" ]]; then
	post_process=('|' jq-repl)
else
	if [[ -n "${JQ:-}" ]]; then
		post_process=('|' jq -S "'$JQ'")
	else
		post_process=()
	fi
fi

>/dev/stderr echo "portable:"
{ echo -n "$("${XH[@]}" "${VERB_URL[@]}" "$@" "${OPTS[@]}" --curl)"; echo " -s ${post_process[*]}"; } | tee /dev/stderr | primarycopy
>/dev/stderr echo

cmd=("${XH[@]}" "${VERB_URL[@]}" "$@" --ignore-stdin "${opts[@]}" "${OPTS[@]}")

>/dev/stderr echo "executing:"
{ echo "$(printf '%q ' "${cmd[@]}")""${post_process[*]}"; echo; } | tee /dev/stderr | bash
