#!/bin/bash

set -Eeo pipefail

### skip cygwin
[[ -n "$OS" ]] && [[ "$OS" == "Windows_NT" ]] && exit 1

### check vpn connected
{
	ip route | grep -P 'default(?:.*?)\sdev\s(?:tun|gpd)' \
	|| ip route | grep -P '10\.[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\s+dev\s+(tun|enp0|wlp0)'
} &>/dev/null
