#!/bin/bash

set -Eeo pipefail

### skip cygwin
[[ -n "$OS" ]] && [[ "$OS" == "Windows_NT" ]] && exit 1

### check vpn connected
{
	ip route | grep -E 'default\sdev\stun' || ip route | grep -E '10\.[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\s+dev\s+(tun|enp0)'
} &> /dev/null
