#!/usr/bin/env bash

# qemu-system-x86_64 -device usb-host,help

set -Eeuo pipefail


# BUS="2"
# PORT="1"

VENDOR="0x090c"
PRODUCT="0x1000"

CMD=(
	-audiodev "pa,id=snd0"
	-bios /usr/share/ovmf/x64/OVMF.4m.fd
	-cpu host
	-device ich9-intel-hda
	-device "hda-output,audiodev=snd0"
	-device "qemu-xhci,id=xhci"
	-device "usb-host,vendorid=$VENDOR,productid=$PRODUCT"
	# -device "usb-host,hostbus=$BUS,hostport=$PORT"
	-drive "file=$1,if=virtio,index=1,media=cdrom"
	-enable-kvm
	-k en-us
	-m 4G
	-nic "user,model=virtio-net-pci"
	-no-reboot
	-smp 2
	-vga virtio
)

exec qemu-system-x86_64 "${CMD[@]}"
