#!/usr/bin/env bash

set -Eeuo pipefail

query='.'

eval set -- "$(getopt --options 'q:' --longoptions 'query:' -- "$@")"

# shellcheck disable=SC2078
while [ : ]; do
	case "$1" in
		-q | --query)
			query="$2"
			shift 2
			;;
		--) shift;
			break
			;;
	esac
done

if [[ -z "${1:-}" ]] || [[ $1 == "-" ]]; then
	input=$(mktemp)
	trap 'rm -f "$input"' EXIT
	cat /dev/stdin > "$input"
else
	input="$1"
fi

if [[ -x "$(command -v json-pretty)" ]]; then
	prettify=(json-pretty --no-filename --color=always)
else
	prettify=(jq -SC)
fi

FZF_CMD=(
	fzf
	--ansi
	--bind="alt-p:unbind(alt-p)"
	--bind="ctrl-c:become(true)"
	--bind="ctrl-j:preview-down"
	--bind="ctrl-k:preview-up"
	--bind="ctrl-m:execute(jq {q} \"$input\" | ${prettify[*]} | less)"
	--bind="ctrl-x:become(echo jq -S \"{q}\" >/dev/stderr; jq -S {q} \"$input\")"
	--bind="ctrl-y:execute-silent(echo -n {q} | clipcopy)"
	--bind="end:preview-bottom"
	--bind="esc:execute-silent(echo -n {q} | clipcopy)+change-query($query)"
	--bind="home:preview-top"
	--bind="page-down:preview-page-down"
	--bind="page-up:preview-page-up"
	--disabled
	--header='C-c:exit C-j:pgdn C-k:pgup C-x:dump C-y:yank Enter:view Esc:reset'
	--preview-window='up:95%:border-bottom:wrap:nohidden'
	--preview="jq {q} \"$input\" | ${prettify[*]}"
	--print-query
	--query="$query"
)

exec "${FZF_CMD[@]}"
