#!/usr/bin/env bash

set -Eeuo pipefail

query='.'

eval set -- "$(getopt --options 'q:' --longoptions 'query:' -- "$@")"

# shellcheck disable=SC2078
while [ : ]; do
	case "$1" in
		-q | --query)
			query="$2"
			shift 2
			;;
		--) shift;
			break
			;;
	esac
done

if [[ -z "${1:-}" ]] || [[ $1 == "-" ]]; then
	input=$(mktemp)
	trap 'rm -f "$input"' EXIT
	cat /dev/stdin > "$input"
else
	input="$1"
fi

FZF_CMD=(
	fzf
	--bind="ctrl-d:execute(echo {q}; echo; jq -S -r {q} \"$input\")+abort"
	--bind="ctrl-m:execute(jq -r {q} \"$input\" | json-pretty --color=always | less)"
	--bind="ctrl-y:execute-silent(echo -n {q} | clipcopy)"
	--bind="esc:execute-silent(echo -n {q} | clipcopy)+change-query($query)"
	--disabled
	--preview="jq -r {q} \"$input\" | json-pretty --color=always"
	--preview-window='up:95%:border-bottom:wrap:nohidden'
	--print-query
	--query="$query"
)

"${FZF_CMD[@]}"
