#!/usr/bin/env bash

set -Eeuo pipefail

if [[ -n "${1:-}" && -t 0 && -r "$1" ]]; then
	name="$(basename -- "$1")"
	base="${name%.*}"

	exec sqlite-utils insert --alter --nl -- "$base.db" "$base" "$name"
elif [[ -n "${1:-}" && ! -t 0 ]]; then
	exec sqlite-utils insert --alter --nl -- "$1.db" "$1" -
else
	>&2 echo provide a file or STDIN and a table name
fi
