#!/bin/bash

set -Eeuo pipefail

command kubectl get --cluster "$(kubectl-management-cluster)" releases.shipper.booking.com -o json 2>/dev/null \
	| jq -r '.items[] | select(.status.achievedStep.name != "full on") | .metadata.name'
