#!/usr/bin/env -S perl -CALS

use v5.36;

use Getopt::Long qw(:config auto_version bundling no_ignore_case);

GetOptions(
    'left|l'  => \my $left_only,
    'right|r' => \my $right_only,
) or die "Unable to process command line options\n";

$left_only && $right_only and die "Cannot choose both sides\n";
-t 0 and die "STDIN must be provided (lines which are going to be split)\n";
@ARGV == 1 or die "Split regex must be provided\n";

my $arg_regex = shift @ARGV;
my $regex     = qr{$arg_regex};

while (defined(my $line = <STDIN>)) {
    chomp $line;
    my ($left, $right) = split $regex, $line, 2;
    say {*STDOUT} $left  // '' unless $right_only;
    say {*STDERR} $right // '' unless $right_only || $left_only;
    say {*STDOUT} $right // '' unless $left_only;
}

__END__
