#!/usr/bin/env bash

set -Eeuo pipefail

quote-if-necessary() {
	[[ -n "$1" ]] || return 0

	local escaped
	escaped=$(printf '%q' "$1")

	if [[ "$1" == "$escaped" ]]; then
		echo -n "$1"
	else
		# it's possible to echo escaped string here, but quoted looks better
		echo -n "${line@Q}"
	fi
}

if read -r line || [[ -n "$line" ]]; then
	quote-if-necessary "$line"
fi

while read -r line || [[ -n "$line" ]]; do
	echo -n ' ' && quote-if-necessary "$line"
done

# mapfile -t DATA
# echo "${DATA[@]@Q}"
