#!/usr/bin/env bash

set -Eeuo pipefail

dir="${1:-/media/nfs/home/music}"

function list_files() {
	cd "$dir"
	while read -r line; do
		echo "$line	mpv --quiet --no-osc --term-osd=force --no-audio-display -- \"${dir}/$line\""
	done < <(fd -t dir --min-depth 2 --max-depth 4 --relative-path)
}

list_files | sort | fzf-execute
