#!/usr/bin/env bash

set -Eeuo pipefail

dir="${PASSWORD_STORE_DIR:-${XDG_DATA_HOME}/password-store}"
cd "$dir" || exit 1

function list_files() {
	shopt -s nullglob globstar

	password_files=(**/*.gpg)
	password_files=("${password_files[@]%.gpg*}")

	for file in "${password_files[@]}"; do
		printf $'%s\tpass2clipboard %s &>/dev/null\n' "$file" "${file@Q}"
	done
}

list_files | sort | fzf-execute
