#!/usr/bin/env zsh

set -Eeuo pipefail

DIR="${1:-/media/nfs/home/music}"

function list_files() {
	(
		cd "$DIR"
		while read -r LINE; do
			echo "$LINE	mpv --quiet --no-osc --term-osd=force --no-audio-display -- \"${DIR}/$LINE\""
		done < <(fd --no-ignore -t d -E '@eaDir' --relative-path)
	) | sort
}

list_files | fzf-execute
