#!/usr/bin/env zsh

set -Eeuo pipefail

FILE="$XDG_CACHE_HOME/mpv/history.log"

perl - "$FILE" <<'END_SCRIPT' | fzf-execute --bind='ctrl-y:execute-silent(echo -n {2} | perl -nE "print m/\"(.+)\"$/" | clipcopy)'
	use v5.34;

	my $fn = $ARGV[0];

	chomp(my @lines = <<>>);

	my %d;

	foreach my $line (@lines) {
		my ($time, $title, $cmd, $path) = $line =~ m/^(\[.+?\])\t(.+?)\t(.+)\t(.+)$/;

		$d{$path} = [sprintf("%s	%s	%s", $title, $cmd, $path), $time, $line];
	}

	END {
		my @result = sort {$a->[1] cmp $b->[1]} values %d;
		say {*STDOUT} ($_->[0]) foreach reverse @result;
		open(my $fh, '>', $fn)
			or die "Unable to open file: $fn\n";
		say {$fh} ($_->[2]) foreach @result;
	}
END_SCRIPT
