#!/usr/bin/env bash

set -Eeuo pipefail

if [[ -n "$(command -v delta)"  ]]; then
	LOG_PAGER="delta"
else
	LOG_PAGER="$PAGER"
fi

if [[ -n "$*" ]]; then
	query=${1}
	shift
fi

CMD=(
	--ansi
	--bind="alt-o:execute-silent(git switch --detach {1})+abort"
	--bind="alt-p:toggle-preview,ctrl-alt-w:toggle-preview-wrap,ctrl-s:toggle-sort"
	--bind="ctrl-m:execute(show-commit {1} | $LOG_PAGER)"
	--bind="ctrl-n:preview-down,ctrl-p:preview-up"
	--cmd-prompt="search commit > "
	--cmd-query="$query"
	--cmd="git-log-wrapper ${*@Q} -P -G '{}'"
	--interactive
	--no-multi
	--no-sort
	--preview-window="right:60%:border-left:wrap"
	--preview="show-commit {1}"
	--reverse
	--tabstop=4
)

exec sk "${CMD[@]}"
