#!/usr/bin/env bash
# shellcheck disable=SC2016

set -Eeuo pipefail

[[ -x "$(command -v argc)" ]] || {
    echo "'argc' helper is required. Please install from https://github.com/sigoden/argc" >&2
    exit 2
}

# @describe Quick access to ruby doc

# @meta version 1.0.0
# @meta combine-shorts
# @meta require-tools fzf-table,jq

# @flag -j --json Output JSON

eval "$(argc --argc-eval "$0" "$@")"

# => -------------------------------------------------------------------------------------------------------------- {{{1

function ri-items-get() {
    ri --all -l | jq -nR '[inputs]'
}

if [[ -n "${argc_json:-}" ]]; then
    ri-items-get
elif [[ -t 1 ]]; then
    export FZF_RELOAD_CMD="$0"

    fzf_args=(
        --bind='ctrl-m:execute(ri -f markdown {1} | glow -p)'
        --bind="alt-g:execute(gum input | xargs -r ri -f markdown | glow -p)"
        --footer="alt-g:input enter:inspect | A-b:browse A-p:preview"
        --preview='ri -f markdown -w $FZF_PREVIEW_COLUMNS {1} | glow -n -w $FZF_PREVIEW_COLUMNS'
        --preview-window="right:50%:border-left:wrap:nohidden,<55(hidden)"
        --prompt="ruby > "
        --with-nth="3.."
    )
    "$0" | fzf-table "${fzf_args[@]}"
else
    source "$HOME/.local/lib/shell/data-processing.bash"

    jq_fields=(
        '_id;\(.)'
        '!_url!https://docs.ruby-lang.org/en/master/\(gsub("::"; "/")).html'
        'topic;\(.)'
    )

    "$0" -j | json-array-to-tsv 'sort' "${jq_fields[@]}"
fi
