#!/usr/bin/env bash

set -Eeuo pipefail

cat << "EOF" | fzf-execute
lock				loginctl lock-session
logout				qdbus org.kde.ksmserver /KSMServer logout 0 0 3 || loginctl terminate-session self
suspend/sleep		systemctl suspend
hibernate			systemctl hibernate
hybrid				systemctl hybrid-sleep
reboot/restart		systemctl reboot
poweroff/shutdown	systemctl poweroff
UEFI/firmware		systemctl reboot --firmware
EOF
