#!/usr/bin/env bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"
FOLDER="${1:-/media/nfs/home/doc/@technical}"

function list_files() {
	(
		cd "$FOLDER"
		while read -r LINE; do
			if [[ "$LINE" =~ \.pdf|\.djvu ]]; then
				echo "$LINE	zathura - <\"${FOLDER}/$LINE\""
			elif [[ "$LINE" =~ \.fb2|\.epub|\.ePub ]]; then
				echo "$LINE	xdg-open \"${FOLDER}/$LINE\""
			fi
		done < <(fd --no-ignore -t file -e pdf -e djvu -e fb2 -e epub --relative-path)
	) | sort
}

list_files | fzf-execute
