#!/usr/bin/env bash

# => header (source able) ----------------------------------------------------------------------------------------- {{{1

function klipper-item-action() {
	busctl --user --json=short call org.kde.klipper /klipper org.kde.klipper.klipper -- showKlipperManuallyInvokeActionMenu
}
export -f klipper-item-action

function klipper-item-get() {
	busctl --user --json=short call org.kde.klipper /klipper org.kde.klipper.klipper -- getClipboardHistoryItem i "$1" \
		| jq '.data[0]'
}
export -f klipper-item-get

function klipper-item-set() {
	# don't use this, the API is a crap. It should set by id, not by content
	# (it's quite tedious to pass text with special symbols and quotes as a command line argument)
	# busctl --user --json=short call org.kde.klipper /klipper org.kde.klipper.klipper -- setClipboardContents s "$1"
	clipcopy "$1"
}
export -f klipper-item-set

function klipper-items-clear() {
	busctl --user --json=short call org.kde.klipper /klipper org.kde.klipper.klipper -- clearClipboardHistory
}
export -f klipper-items-clear

function klipper-items-get() {
	busctl --user --json=short call org.kde.klipper /klipper org.kde.klipper.klipper -- getClipboardHistoryMenu \
		| jq -r '.data[]'
}
export -f klipper-items-get

# => body (executable) -------------------------------------------------------------------------------------------- {{{1

if [[ "$0" == "${BASH_SOURCE[0]:-}" ]]; then # hide all executions under condition to make file source able
	set -Eeuo pipefail

	function help() {
		name=$(basename "$0")
		echo "$name - Browse clipboard history in terminal"
		echo
		echo "Usage:"
		echo "    $name [options]"
		echo
		echo "Command options:"
		echo "   -h, --help         print help and exit"
		echo "   -j, --json         print as json (suppress UI)"
	} &>/dev/stderr

	args=$(getopt --name="$0" --options 'hj' --longoptions 'help,json' -- "$@")
	eval set -- "$args"

	while ((1)); do
		case "$1" in
			-h | --help) help; exit ;;
			-j | --json) json='1'; shift ;;
			--) shift; break ;;
		esac
	done

	if [[ -n "${json:-}" ]]; then
		klipper-items-get
	elif [[ -t 1 ]]; then
		fzf_cmd=(
			fzf
			--ansi
			--bind="alt-p:toggle-preview,ctrl-s:toggle-sort,ctrl-t:toggle-track"
			--bind="ctrl-d:half-page-down,ctrl-u:half-page-up,home:top"
			--bind="ctrl-e:toggle-preview-wrap,ctrl-n:preview-down,ctrl-p:preview-up"
			--bind="ctrl-w:backward-kill-word,esc:cancel"
			--delimiter="\t"
			--listen
			--no-multi
			--reverse
			--scroll-off=4
			--tabstop=4
			--with-nth="2.."
		)
		fzf_args=(
			--bind="alt-c:become(klipper-items-clear)"
			--bind="alt-i:execute(klipper-item-get {1} | jq -j | bat --color always --style numbers,grid --paging always --wrap never)"
			--bind="alt-enter:become(klipper-item-get {1} | jq -j | primarycopy)"
			--bind="alt-s:become(klipper-item-get {1} | jq -j | secondarycopy)"
			--bind="ctrl-m:become(klipper-item-get {1} | jq -j | clipcopy)"
			--bind="ctrl-r:reload($0)"
			--bind="ctrl-y:become(klipper-item-get {1} | jq -j | clipcopy)"
			--header='C-j/k:move C-r:reload A-c:clear A-i:inspect A-p:preview Enter:select'
			--preview-window="right:40%:border-left:nowrap:nohidden"
			--preview="klipper-item-get {1} | jq -j | bat --color always --style plain"
			--prompt="clipboard history > "
		)
		export SHELL="$BASH" # enforce bash for all fzf sub shells
		"$0" | "${fzf_cmd[@]}" "${fzf_args[@]}"
	else
		"$0" -j | jq -r 'to_entries | map([.key, .value]).[] | select(.[1] | test("▨") | not) | @tsv'
	fi
fi
