#!/usr/bin/env zsh

set -Eeuo pipefail

DIR=${PASSWORD_STORE_DIR:-${XDG_DATA_HOME}/password-store}

function list_files() {
	# shopt -s nullglob globstar
	setopt NULLGLOB

	password_files=("$DIR"/**/*.gpg)
	password_files=("${password_files[@]#*"$DIR/"}")
	password_files=("${password_files[@]%".gpg"*}")
	for FILE in "${password_files[@]}"; do
		printf "%s	pass-to-clipboard \"$DIR/%s\" &>/dev/null\n" "$FILE" "$FILE"
	done
}

list_files | sort | fzf-execute
