#!/usr/bin/env bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"
man -k . \
	| perl -nlE '($n, $s, $t) = m/\A(.+?) \s+ [(] (\d+.*) [)] \s+ - \s+ (.+) \z/xx; next unless $n; say sprintf "%-40s (%d) %s\texport MANPAGER=\"nvim +Man!\"; man -s $s $n", $n, $s, $t' \
	| sort -u \
	| fzf-execute-term
