#!/usr/bin/env bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"
FOLDER="${XDG_DATA_HOME}/cheatsheet"

function list_files() {
	shopt -s nullglob globstar

	FILES=("$FOLDER"/*)
	FILES=("${FILES[@]#*"$FOLDER/"}")

	for FILE in "${FILES[@]}"; do
		printf "%s	zathura \"${FOLDER}/%s\" &>/dev/null\n" "$FILE" "$FILE"
	done
}

list_files | fzf-execute
