#!/usr/bin/env zsh

set -Eeuo pipefail

DIR="${1:-/media/nfs/home/video}"

function list_files() {
	(
		cd "$DIR"
		while read -r LINE; do
			echo "$LINE	mpv --quiet -- \"${DIR}/$LINE\""
		done < <(fd --no-ignore -t file -e webm -e mkv -e avi -e mp4 -e ts --relative-path)
	) | sort
}

list_files | fzf-execute
