#!/usr/bin/env zsh

set -Eo pipefail

export PERLBREW_ROOT="${PERLBREW_ROOT:-$XDG_DATA_HOME/perlbrew}"
export PERLBREW_HOME="$PERLBREW_ROOT"

# shellcheck source=/dev/null
[[ -r "$PERLBREW_ROOT/etc/bashrc" ]] && source "$PERLBREW_ROOT/etc/bashrc"

SCRIPT=$(cat <<- 'EOSCRIPT'
	($n, $s, $t) = m/\A(.+?) \s+ [(] (\d+.*) [)] \s+ - \s+ (.+) \z/xx;
	$m = '\":nnoremap <buffer> q :quitall<CR>\"';
	$r{"$n/$s"} = sprintf(qq{%-40s (%d) %s\texport MANPAGER="nvim +Man! -c $m"; man -s $s $n}, $n, $s, $t) if $n;
	END { say $r{$_} foreach sort keys %r }
EOSCRIPT
)

man -ak .                 \
	| perl -nlE "$SCRIPT" \
	| fzf-execute-term
