#!/usr/bin/env zsh

set -Eeuo pipefail

FOLDER="${1:-/media/nfs/home/music}"

function list_files() {
	(
		cd "$FOLDER"
		while read -r LINE; do
			echo "$LINE	mpv --quiet -- \"${FOLDER}/$LINE\""
		done < <(fd --no-ignore -t d -E '@eaDir' --relative-path)
	) | sort
}

list_files | fzf-execute
