#!/usr/bin/env zsh

set -Eeuo pipefail

DIR="${1:-/media/nfs/home/doc/@technical}"

function list_files() {
	(
		cd "$DIR"
		while read -r LINE; do
			if [[ "$LINE" =~ \.pdf\|\.djvu ]]; then
				echo "$LINE	zathura - <\"${DIR}/$LINE\""
			elif [[ "$LINE" =~ \.fb2\|\.epub\|\.ePub ]]; then
				echo "$LINE	xdg-open \"${DIR}/$LINE\""
			fi
		done < <(fd --no-ignore -t file -e pdf -e djvu -e fb2 -e epub --relative-path)
	) | sort
}

list_files | fzf-execute
