#!/usr/bin/env bash

set -Eeuo pipefail

if [[ -n "$(command -v delta)"  ]]; then
	pager="delta"
else
	pager="${PAGER:-less}"
fi

if [[ -n "$*" ]]; then
	query=${1}
	shift
fi

source "$HOME/.local/lib/shell/fzf.bash"

sk_args=(
	--bind="alt-o:execute-silent(git switch --detach {1})+abort"
	--bind="ctrl-m:execute(show-commit {1} | $pager)"
	--cmd-prompt="search comment > "
	--cmd-query="${query:-}"
	--cmd="git-log-wrapper ${*@Q} -P --grep '{}'"
	--delimiter=" "
	--interactive
	--no-sort
	--preview-window="right:60%:border-left:wrap:nohidden"
	--preview="show-commit {1}"
)

sk-exec "${sk_args[@]}"
