#!/usr/bin/env bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"
FOLDER="${1:-/media/nfs/home/doc/@technical}"

function list_files() {
	(
		cd "$FOLDER"
		while read -r LINE; do
			echo "$LINE	cat \"${FOLDER}/$LINE\" | zathura - &>/dev/null"
		done <<<"$(fd -t file -e pdf -e djvu --relative-path)"
	) | sort
}

list_files | fzf-execute
