#!/usr/bin/env bash

set -Eeuo pipefail

file=${1:-$XDG_RUNTIME_DIR/test.sh}

[[ -r "$file" ]] || {
    {
        echo '#!/usr/bin/env bash'
        echo
        echo 'set -Eeuo pipefail'
    } >> "$file"

    chmod a+x "$file"
}

"${VISUAL:-vim}" "$file"
