#!/usr/bin/env bash

set -Eeuo pipefail

[[ -r "$1" ]] && exit 1

{
	echo '#!/usr/bin/env -S deno --allow-env --allow-ffi --allow-net --allow-read --allow-sys'
	echo
	echo '# https://docs.deno.com/api/node/'
	echo '# https://docs.deno.com/runtime/fundamentals/standard_library/'
} >> "$1"

chmod a+x "$1"

"${VISUAL:-vim}" "$1"
