#!/usr/bin/env bash

set -Eeuo pipefail

file=${1:-$XDG_RUNTIME_DIR/test.ts}

[[ -r "$file" ]] || {
    {
        echo '#!/usr/bin/env -S deno --allow-env --allow-ffi --allow-net --allow-read --allow-sys'
        echo
        echo '# https://docs.deno.com/api/node/'
        echo '# https://docs.deno.com/runtime/fundamentals/standard_library/'
    } >> "$file"

    chmod a+x "$file"
}

"${VISUAL:-vim}" "$file"
