#!/usr/bin/env bash

set -Eeuo pipefail

file=${1:-$XDG_RUNTIME_DIR/test.pl}

[[ -r "$file" ]] || {
    {
        echo '#!/usr/bin/env -S perl -CALS'
        echo
        echo 'use v5.40;'
        echo 'use experimental qw(class declared_refs defer refaliasing);'
        echo
        echo '__END__'
    } >> "$file"

    chmod a+x "$file"
}

"${VISUAL:-vim}" "$file"
