#!/usr/bin/env bash

set -Eeuo pipefail

file=${1:-$XDG_RUNTIME_DIR/test.py}

[[ -r "$file" ]] || {
    {
        echo '#!/usr/bin/env python3'
        echo
        echo 'import logging'
        echo 'from pprint import pprint'
        echo
        echo 'logging.basicConfig(format="%(asctime)s " + logging.BASIC_FORMAT, level=logging.DEBUG)'
    } >> "$file"

    chmod a+x "$file"
}

"${VISUAL:-vim}" "$file"
