#!/usr/bin/env bash

set -Euo pipefail

SRC=${SRC:-"home.ams::"}
DST=${DST:-"./"}

if [[ $# -eq 0 ]]; then
	mapfile -t DIRS < <(fd --no-hidden -t d -d 1)
else
	DIRS=("$@")
fi

RSYNC_PARAMS=(
	--sparse
	--exclude="#recycle"
	--exclude="#snapshot"
	--exclude=".Trash-*"
	--exclude="@eaDir"
	--rsh=ssh
	--delete
	--dry-run
	-i
	--info=progress2
	-HhrtlDXx
	--no-owner
	--no-group
	--omit-dir-times
	--checksum
)

for DIR in "${DIRS[@]}"; do
	echo -n "$(tput setaf 3)"
	echo "Comparing ${DST}${DIR} with ${SRC}..."
	echo -n "$(tput sgr0)"

	rsync "${RSYNC_PARAMS[@]}" "${SRC}${DIR}/" "${DST}${DIR}/"
done
