#!/usr/bin/env bash

set -eEuo pipefail

function recursively_remove_write_permission() {
	REAL_PATH="$1"
	while [[ "$REAL_PATH" != "/home/$USR" ]] && [[ "$REAL_PATH" != "/" ]]; do
		REAL_PATH="$(dirname $REAL_PATH)"
		sudo chmod go-w "$REAL_PATH"
	done
}

renice -n 5 "$$" > /dev/null

USR="${1:-$USER}"
GRP="$(id -ng "$USR")"

shopt -s dotglob

sudo chown "${USR}:${GRP}" -R -- *
sudo chmod -R a+rX,ug+w,o-w -- *
sudo fd -u -E "@eaDir" -t d -x chmod g+s --

if [[ -e ".gnupg" ]]; then
	REAL_PATH="$(realpath .gnupg)"
	sudo chmod -R u=rwX,go-rwx,g-s "$REAL_PATH"
	recursively_remove_write_permission "$REAL_PATH"
fi

if [[ -e ".ssh" ]]; then
	REAL_PATH="$(realpath .ssh)"
	sudo chmod -R u=rwX,go-rwx,g-s "$REAL_PATH"
	recursively_remove_write_permission "$REAL_PATH"
fi

if [[ -e ".local/share/containers" ]]; then
	sudo chmod -R ug=rwX,o-rwx,g-s "$(realpath .local/share/containers)"
fi
