#!/usr/bin/env bash

set -Euo pipefail

SOURCE='home.ams::'
DEST='.'

if [[ $# -eq 0 ]]; then
	mapfile -t DIRS < <(fd --no-hidden -t d -d 1)
else
	DIRS=("$@")
fi

RSYNC_PARAMS=(
	--sparse
	--exclude="#recycle"
	--exclude="#snapshot"
	--exclude=".Trash-*"
	--exclude="@eaDir"
	--rsh=ssh
	--delete
	--info=progress2
	-P
	-HahXx
)
for DIR in "${DIRS[@]}"; do
	echo -n "$(tput setaf 3)"
	echo "Synchronizing $DIR..."
	echo -n "$(tput sgr0)"

	rsync "${RSYNC_PARAMS[@]}" "${SOURCE}${DIR}/" "${DEST}/${DIR}/"
done
