#!/usr/bin/env bash

set -Euo pipefail

source "$HOME/.local/lib/shell/rsync.bash"

rsync_params=(
	"${RSYNC_DEFAULT_PARAMS[@]}"
	"${RSYNC_COPY_PARAMS[@]}"
	"${RSYNC_NAS_PARAMS_COMMON[@]}"
	-P
)
operation="Copying"

args=$(getopt --name="$0" --options 'cs' --longoptions 'checksum,sync' -- "$@")
eval set -- "$args"

while ((1)); do
	case "$1" in
		-c | --checksum) rsync_params+=(--checksum); shift ;;
		-s | --sync) rsync_params+=(--delete); operation="Synchronizing"; shift ;;
		--) shift; break ;;
	esac
done

src=${src:-"home.ams::"}
dst=${dst:-"./"}

if [[ $# -eq 0 ]]; then
	mapfile -t dirs < <(fd --no-hidden -t d -d 1)
else
	dirs=("$@")
fi

source "$HOME/.local/lib/shell/color.bash"

for dir in "${dirs[@]}"; do
	echo -e "${FG[olive]}$operation $dir from ${src}...${FX[reset]}"

	rsync "${rsync_params[@]}" "${src}${dir}/" "${dst}${dir}/"
done
