#!/usr/bin/env bash

set -Euo pipefail

operation="Comparing"
if [[ -x "$(command -v tsp)" ]]; then
	background="1"
fi

args=$(getopt --name="$0" --options 'cf' --longoptions 'checksum,foreground' -- "$@")
eval set -- "$args"

while ((1)); do
	case "$1" in
		-c | --checksum) checksum="1"; shift ;;
		-f | --foreground) background="0"; shift ;;
		--) shift; break ;;
	esac
done

export IS_NAS="1"

source "$HOME/.local/lib/shell/rsync.bash"

rsync_params+=(
	"${RSYNC_DEFAULT_PARAMS[@]}"
	"${RSYNC_NAS_PARAMS_COMMON[@]}"
)

if [[ "${checksum:-}" == "1" ]]; then
	rsync_params+=("${RSYNC_DIFF_PARAMS_CS[@]}")
else
	rsync_params+=("${RSYNC_DIFF_PARAMS[@]}")
fi

if [[ "${background:-1}" == "0" && -t 1 ]]; then
	rsync_params+=("${RSYNC_INFO_TTY[@]}")
else
	runner=(tsp)
	rsync_params+=("${RSYNC_INFO_FILE[@]}")
fi

src="${src:-"./"}"
dst="${dst:-"home3.ams::"}"

if [[ $# -eq 0 ]]; then
	mapfile -t dirs < <(fd --no-hidden -t d -d 1 | sed 's|/$||')
else
	dirs=("$@")
fi

source "$HOME/.local/lib/shell/color.bash"

for dir in "${dirs[@]}"; do
	echo -e "${FG[olive]}$operation ${src}$dir with ${dst}$dir...${FX[reset]}"

	"${runner[@]}" rsync "${rsync_params[@]}" "${src}$dir/" "${dst}$dir/"
done
