#!/usr/bin/env bash

set -Euo pipefail

SRC=${SRC:-"home.ams::"}
DST=${DST:-"./"}

# shellcheck disable=SC1090
source "$(realpath -Ls "$(dirname "$0")/../lib/shell/rsync.bash")"

if [[ $# -eq 0 ]]; then
	mapfile -t DIRS < <(fd --no-hidden -t d -d 1)
else
	DIRS=("$@")
fi

rsync_params=(
	"${RSYNC_DEFAULT_PARAMS[@]}"
	"${RSYNC_DIFF_PARAMS[@]}"
	--rsh=ssh
)

for DIR in "${DIRS[@]}"; do
	echo -n "$(tput setaf 3)"
	echo "Comparing ${DST}${DIR} with ${SRC}..."
	echo -n "$(tput sgr0)"

	rsync "${rsync_params[@]}" "${SRC}${DIR}/" "${DST}${DIR}/"
done
