#!/usr/bin/env bash

set -Eeuo pipefail

ITEMS=("default" "kickstart" "LazyVim" "NvChad" "AstroNvim")
CONFIG=$(printf "%s\n" "${ITEMS[@]}" | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)

if [[ -z $CONFIG ]]; then
    echo "Nothing selected"
    return 0
elif [[ $CONFIG != "default" ]]; then
    export NVIM_APPNAME=$CONFIG
    unset VIMINIT
fi

exec nvim "$@"
