#!/usr/bin/env bash

set -Eeuo pipefail

dir="$(dirname "$1")"
name="$(basename "$1")"
tag="$(echo -n "${name%%.*}" | perl -nE 'print lc')"
root="$(git -C "$dir" rev-parse --show-superproject-working-tree --show-toplevel | head -1)"

set -x
docker build --rm -t "$tag" -f "$1" "$root"
