#!/usr/bin/env bash

set -Euo pipefail

STORE=${PASSWORD_STORE_DIR:-${XDG_DATA_HOME}/password-store}
PASS_PATH="$(realpath --relative-to="$STORE" "$1")"
PASS_PATH="${PASS_PATH%".gpg"*}"
USERNAME=$(basename "$PASS_PATH")

gpg --card-status &>/dev/null

MSG=''

{
	pass show --clip "$PASS_PATH" && MSG="${MSG}
	Password copied to clipboard"
	} || {
	notify-send "Something went wrong" "Error: $?" -i dialog-password
	exit 1
}

echo -n "$USERNAME" | secondarycopy \
	&& MSG="Username copied to secondary buffer"

PRIMARY="$(pass otp code "$PASS_PATH" || echo -n "$USERNAME")"
echo -n "$PRIMARY" | primarycopy
MSG="${MSG}
OTP code $PRIMARY copied to primary buffer"

notify-send "$MSG" "$USERNAME" -i dialog-password
