#!/usr/bin/env bash

set -Eeuo pipefail

DOMAIN_PARTS=(paste . boo king . com)
DOMAIN=$(printf "%s" "${DOMAIN_PARTS[@]}")
CMD=(
	curl --noproxy "$DOMAIN" -s
	-d "author=$USER"
	-d "syntax=0"
	-d "lifespan=4"
	--data-urlencode pasteEnter@-
	"https://$DOMAIN/api"
)

RESPONSE="$(cat "$@" | "${CMD[@]}")"
ERROR="$(echo "$RESPONSE" | jq -r .error)"

if [[ "$ERROR" = "0" ]]; then
	URL=$(echo "$RESPONSE" | jq -r .url)
	[[ -n "$URL" ]] && {
		echo "Paste is saved to: $URL"
		echo -n "$URL" | clipcopy
	}
else
	echo "Error: $(echo "$RESPONSE" | jq -r .message)"
fi
