#!/usr/bin/env bash

set -Eeuo pipefail

# primarycopy - Copy data to the PRIMARY buffer
#
# Usage:
#  <command> | primarycopy      - copies stdin to primary
#  primarycopy <file> <file>... - copies file's contents to primary

case "$OSTYPE" in
	cygwin* | msys*)
		cat "$@" >/dev/primary
		;;
	*)
		if [[ -n "$(command -v xsel)" ]]; then
			cat "$@" | xsel --input --primary &>/dev/null
		elif [[ -n "$(command -v xclip)" ]]; then
			cat "$@" | xclip -sel p &>/dev/null
		else
			echo "primarycopy: Platform $OSTYPE not supported or xclip/xsel not installed" >&2
			exit 1
		fi
		;;
esac
