#!/usr/bin/env bash

set -Eeuo pipefail

shopt -s nullglob

bios=()
options=()

[[ "$1" =~ bios ]] || {
    bios+=(
        -bios /usr/share/ovmf/x64/OVMF.4m.fd
    )
}

if [[ "$1" =~ usb.qcow2$ ]]; then
    options+=(
        -device "qemu-xhci,id=xhci"
        -device "usb-storage,bus=xhci.0,drive=stick"
        -drive "file=$1,if=none,id=stick,format=qcow2"
    )
elif [[ "$1" =~ qcow2$ ]]; then
    name="${1%.qcow2}"
    index=0
    for file in "${name::-1}"*.qcow2; do
        [[ "$file" =~ nvme\.qcow2$ ]] && continue
        options+=(-drive "file=$file,if=virtio,index=$index,media=disk,format=qcow2")
        index=$(( ++index ))
    done
    for file in "${name::-1}"*-nvme.qcow2; do
        options+=(-drive "file=$file,if=none,id=nvm")
    done
else
    options+=(
        -drive "file=$1,if=virtio,index=0,media=disk,format=raw"
    )
fi

args=(
    -audiodev "pa,id=snd0"
    "${bios[@]}"
    -cpu host
    -device ich9-intel-hda
    -device "hda-output,audiodev=snd0"
    # -device "nvme,serial=deadbeef,drive=nvm"
    # -netdev "bridge,id=hn0"
    # -device "virtio-net-pci,netdev=hn0,id=nic1"
    # -nic "tap,ifname=tap0,romfile=,script=no,downscript=no"
    # -device "virtio-net,netdev=network0"
    # -netdev "tap,id=network0,ifname=tap0,script=no,downscript=no"
    # -device "e1000,netdev=network0,mac=52:55:00:d1:55:01"
    "${options[@]}"
    -display "gtk,zoom-to-fit=on"
    -enable-kvm
    -k en-us
    -m 4G
    -nic "user,model=virtio-net-pci,hostfwd=tcp::2222-:22"
    # -serial stdio
    -smp 2
    # -vga std
    -vga virtio
    # -virtfs "local,path=$HOME/.cache,mount_tag=host0,security_model=passthrough,id=host0"
)

exec qemu-system-x86_64 "${args[@]}"
