#!/usr/bin/env bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"

chosen="$(grep-unicode | LC_ALL='en_US.UTF-8' rofi -dmenu -i -p Unicode | perl -C -aE 'print chr hex $F[0]; exit')"

[[ -n "${chosen}" ]] && {
	echo -n "${chosen}" | clipcopy \
	&& notify-send -i dialog-password "${chosen}" 'Copied to the clipboard'
}
