#!/usr/bin/env bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"
FOLDER="${XDG_DATA_HOME}/cheatsheet"

function list-files() {
	shopt -s nullglob globstar

	FILES=("$FOLDER"/*)
	FILES=("${FILES[@]#*"$FOLDER/"}")

	printf '%s\n' "${FILES[@]}"
}

if (( $# == 0 )); then
	rofi -modi "Cheatsheet:${0} --show" -show Cheatsheet
elif [[ $# -lt 2 ]]; then
	list-files
else
	if [[ "$1" == "--show" ]]; then
		{
			zathura "${FOLDER}/$2" &
		} >/dev/null 2>&1
	fi
fi
