#!/usr/bin/env bash

set -Eeuo pipefail

PATH="$(dirname "$0"):$PATH"

chosen="$(grep-emoji | LC_ALL='en_US.UTF-8' rofi -dmenu -i -p Emoji | sed 's/ > .*//')"

[[ -n "${chosen}" ]] && {
	echo -n "${chosen}" | clipcopy \
	&& notify-send -i dialog-password "${chosen}" 'Copied to the clipboard'
}
