#!/usr/bin/env bash

set -Eeuo pipefail

function list-options() {
	options=(
		"lock"
		"logout"
		"suspend"
		"hibernate"
		"hybrid"
		"reboot/restart"
		"poweroff/shutdown"
	)

	printf '%s\n' "${options[@]}"
}

function action() {
	case "$1" in
		lock)
			loginctl lock-session
			;;
		logout)
			loginctl terminate-session self
			;;
		suspend)
			systemctl suspend
			;;
		hibernate)
			systemctl hibernate
			;;
		hybrid)
			systemctl hybrid-sleep
			;;
		reboot*)
			systemctl reboot
			;;
		poweroff*)
			systemctl poweroff
			;;
		*help)
			echo "Usage: $0 {lock|logout|suspend|hibernate|hybrid|reboot|poweroff}"
			exit 2
			;;
	esac
}

if [[ $# -lt 1 ]]; then
	action "$(list-options | rofi -dmenu -i -p Power)"
elif [[ $# -lt 2 ]]; then
	action "$1"
fi
