#!/usr/bin/env bash

set -Eeuo pipefail

# shellcheck disable=SC1090
source "$(realpath -Ls "$(dirname "$0")/../lib/shell/rsync.bash")"

rsync_params=(
	"${RSYNC_DEFAULT_PARAMS[@]}"
	"${RSYNC_DIFF_PARAMS[@]}"
)

exec rsync "${rsync_params[@]}" "$@"
