#!/usr/bin/env bash

set -Eeuo pipefail

[[ -n "${1:-}" ]] || exit 1

source "$HOME/.local/lib/shell/rsync.bash"

rsync_params=(
	"${RSYNC_DEFAULT_PARAMS[@]}"
	"${RSYNC_COPY_PARAMS[@]}"
)

exec rsync "${rsync_params[@]}" "$@"
