#!/usr/bin/env bash

set -Eeuo pipefail

[[ -n "${1:-}" ]] || exit 1

source "$HOME/.local/lib/shell/rsync.bash"

rsync_params=(
	"${RSYNC_DEFAULT_PARAMS[@]}"
)

current_script="$(basename "$0")"
if [[ "$current_script" =~ -cs$ ]]; then
	rsync_params+=(
		"${RSYNC_DIFF_PARAMS_CS[@]}"
	)
else
	rsync_params+=(
		"${RSYNC_DIFF_PARAMS[@]}"
	)
fi

exec rsync "${rsync_params[@]}" "$@"
