#!/usr/bin/env bash

set -Eeuo pipefail

[[ -n "$1" ]] || exit 1

# shellcheck disable=SC1090
source "$(realpath -Ls "$(dirname "$0")/../lib/shell/rsync.bash")"

rsync_params=(
	"${RSYNC_DEFAULT_PARAMS[@]}"
	"${RSYNC_MOVE_PARAMS[@]}"
)

exec rsync "${rsync_params[@]}" "$@"
