#!/usr/bin/env bash

set -Eeuo pipefail

ISO_NAME=$(basename "$1")
ISO_DIR=$(dirname "$1")

QCOW_NAME="${ISO_NAME/.iso/}.bios.qcow2"
QCOW_PATH="$ISO_DIR/$QCOW_NAME"
[[ -f "$QCOW_PATH" ]] || {
	qemu-img create -f qcow2 "$QCOW_PATH" 128G
}

USB_NAME="${ISO_NAME/.iso/}.bios.usb.qcow2"
USB_PATH="$ISO_DIR/$USB_NAME"
[[ -f "$USB_PATH" ]] || {
	qemu-img create -f qcow2 "$USB_PATH" 8G
}

CMD=(
	-audiodev "pa,id=snd0"
	-cdrom "$1"
	-cpu host
	-device ich9-intel-hda
	-device "hda-output,audiodev=snd0"
	-device "qemu-xhci,id=xhci"
	-device "usb-storage,bus=xhci.0,drive=stick"
	-drive "file=$QCOW_PATH,if=virtio,index=0,media=disk,format=qcow2"
	-drive "file=$1,if=virtio,index=1,media=cdrom"
	-drive "file=$USB_PATH,if=none,id=stick,format=qcow2"
	-display "gtk,zoom-to-fit=on"
	-enable-kvm
	-k en-us
	-m 4G
	-nic "user,model=virtio-net-pci"
	-no-reboot
	# -serial stdio
	-smp 2
	-vga std
	# -virtfs "local,path=$HOME/.cache,mount_tag=host0,security_model=passthrough,id=host0"
)

qemu-system-x86_64 "${CMD[@]}"
