#!/bin/bash

set -Eeuo pipefail

if [[ "$1" =~ usb.qcow2 ]]; then
	OPTIONS=(
		-device "qemu-xhci,id=xhci"
		-device "usb-storage,bus=xhci.0,drive=stick"
		-drive "file=$1,if=none,id=stick,format=qcow2"
	)
else
	OPTIONS=(
		-drive "file=$1,if=virtio,index=0,media=disk,format=qcow2"
	)
fi

CMD=(
	-audiodev "pa,id=snd0"
	-bios /usr/share/ovmf/x64/OVMF.fd
	-cpu host
	-device ich9-intel-hda
	-device "hda-output,audiodev=snd0"
	"${OPTIONS[@]}"
	-enable-kvm
	-k en-us
	-m 4G
	-nic "user,model=virtio-net-pci"
	# -serial stdio
	-smp 2
	-vga std
	# -virtfs "local,path=$HOME/.cache,mount_tag=host0,security_model=passthrough,id=host0"
)

qemu-system-x86_64 "${CMD[@]}"
