#!/usr/bin/env bash

set -Eeo pipefail

PATH="$(dirname "$0"):$PATH"

if [[ -x "$(command -v delta)" ]]; then
	GIT_PAGER="delta"
else
	GIT_PAGER="cat"
fi

git-in-repo && {
	if [[ -n "$*" ]]; then
		REF="$1"
		shift
	else
		REF="HEAD"
	fi

	COMMIT="$(git rev-parse "$REF" 2>/dev/null)"
	[[ -z "$COMMIT" ]] && return

	SHOW_OPTIONS=(--color=always --ignore-space-change)

	if [[ -n "$(git rev-parse --verify "$COMMIT^2" 2>/dev/null)" ]]; then
		# is a merge commit

		if [ -t 1 ]; then
			git show "${SHOW_OPTIONS[@]}" "$COMMIT" "$@" --pretty=fuller
		else
			git --no-pager show "${SHOW_OPTIONS[@]}" "$COMMIT" "$@" --pretty=fuller | $GIT_PAGER
		fi
		echo
		SHOW_OPTIONS+=(--first-parent)

		LEFT_SIDE="$(git rev-parse --verify "$COMMIT^1" 2>/dev/null)"
		COMMIT="$(git rev-parse --verify "$COMMIT^2" 2>/dev/null)"
		SPAN="$LEFT_SIDE..$COMMIT"
	else
		if git gmr &>/dev/null; then
			# has remote
			MAIN_UPSTREAM_BRANCH="$(git gmu 2>/dev/null)"
			MAIN_UPSTREAM_COMMIT="$(git rev-parse "$MAIN_UPSTREAM_BRANCH" 2>/dev/null)"
			if [[ "$MAIN_UPSTREAM_COMMIT" = "$COMMIT" ]]; then
				SPAN="$COMMIT"
			elif git merge-base --is-ancestor "$COMMIT" "$MAIN_UPSTREAM_BRANCH"; then
				SPAN="$COMMIT"
			else
				SPAN="$MAIN_UPSTREAM_BRANCH..$COMMIT"
			fi
		else
			SPAN="$COMMIT"
		fi
	fi

	if [ -t 1 ]; then
		git show "${SHOW_OPTIONS[@]}" "$SPAN" "$@"
	else
		git --no-pager show "${SHOW_OPTIONS[@]}" "$SPAN" "$@" | $GIT_PAGER
	fi
} 2>/dev/null
