#!/usr/bin/env bash

set -Eeuo pipefail

# shellcheck disable=SC2002
if [[ -t 1 ]]; then
	if [[ -x "$(command -v delta)" ]]; then
		pager=("delta")
	else
		pager=("$(git config core.pager)")
	fi
else
	pager=("cat")
fi

function is_merge_commit() {
	local ref="$1"
	&>/dev/null git rev-parse --verify "${ref}^2"
}

git-in-repo && {
	args=$(getopt --name="$0" --options 'd' --longoptions 'diff' -- "$@")
	eval set -- "$args"

	mr_diff="1"
	branch_diff="0"

	while ((1)); do
		case "$1" in
			-d | --diff) branch_diff='1'; shift ;;
			--) shift; break ;;
		esac
	done

	if [[ -n "$*" ]]; then
		ref="$1"
		shift
	else
		ref="HEAD"
	fi

	git rev-parse --verify "$ref" &>/dev/null || return

	log_args=(--color=always --ignore-space-change --pretty=fuller --stat --minimal --patch)
	show_args=(--color=always --ignore-space-change --pretty=fuller --stat)

	if is_merge_commit "$ref"; then
		if [[ "${mr_diff:-}" == "1" ]]; then
			git --no-pager show "${show_args[@]}" --dd --minimal --patch "$ref" "$@"
		else
			git --no-pager show "${show_args[@]}" --no-patch "$ref" "$@"
			echo
			echo
			git --no-pager log "${log_args[@]}" "${ref}^1..${ref}^2"
		fi
	else
		if git main-remote &>/dev/null; then
			commit="$(git rev-parse "$ref" 2>/dev/null)"
			main_upstream_branch="$(git main-upstream 2>/dev/null)"
			main_upstream_commit="$(git rev-parse "$main_upstream_branch" 2>/dev/null)"
			if [[ "$main_upstream_commit" = "$commit" ]]; then
				span="$ref"
			elif git merge-base --is-ancestor "$ref" "$main_upstream_branch"; then
				span="$ref"
			else
				commits="$(git --no-pager log --color=always --oneline "$main_upstream_branch..$ref")"
				if [[ "${branch_diff:-}" == "1" ]] && (( $(echo "$commits" | wc -l) > 1 )); then
					echo "Combined diff for commits:"
					echo "$commits"
					git --no-pager diff "${log_args[@]}" "$main_upstream_branch...$ref" "$@"
					# echo
					# span="$main_upstream_branch..$ref"
				else
					span="$ref"
				fi
			fi
		else
			span="$ref"
		fi

		[[ -n "${span:-}" ]] && git --no-pager show "${show_args[@]}" --show-signature --dd --minimal --patch "$span" "$@"
	fi
} 2>/dev/null | "${pager[@]}"
