#!/usr/bin/env bash

set -Eeuo pipefail

DIR="${1:-$(pwd)}"

[[ -d "$DIR" ]] && {
	stat "$DIR"

	echo "  Type: $(file -b "$DIR")"
	mime=$(file -bi "$1")
	echo "  FILE: $mime"
	echo "  MIME: $(xdg-mime query filetype "$1")"
	echo

	if [[ -x "$(command -v eza)" ]]; then
		eza -laTF -L 3 --color=always --time-style=long-iso --group-directories-first "$DIR"
	else
		tree -Chp -L 3 "$DIR" \
			|| ls -la --color=always
	fi
} 2> /dev/null
