#!/usr/bin/env perl

use v5.40;
use autodie;
use open ':locale';
use utf8;
use warnings     qw(FATAL utf8);
use experimental qw(class declared_refs defer refaliasing);

use Mojo::SQLite qw();
use YAML::XS     qw();

my $database  = $ARGV[0];
my $sql       = Mojo::SQLite->new("sqlite:$database");
my $rows_aref = $sql->db->query("SELECT name, sql FROM sqlite_master WHERE type='table' AND name != 'sqlite_sequence'")
    ->hashes->to_array;

print YAML::XS::Dump($rows_aref);
