#!/usr/bin/env perl

use v5.36;
use autodie;
use open ':locale';
use utf8;
use warnings     qw(FATAL utf8);
use experimental qw(builtin declared_refs defer for_list refaliasing try);

use Getopt::Long qw(:config auto_version bundling no_ignore_case);
use List::Util   qw(min none);
use Pod::Usage   qw(pod2usage);

use Log::Any                qw($log);
use Log::Any::Adapter       qw(Syslog), ('options' => 'pid,ndelay');
use Log::Any::Adapter::Util qw(INFO TRACE WARNING);
use Path::Tiny              qw(path);

my %options = (
    'APPLY'    => 0,
    'BASE_DIR' => '.',
    'IGNORE'   => [],
    'RECURSE'  => 0,
    'VERBOSE'  => 0,
);

sub main() {
    GetOptions(
        'apply|a'    => \$options{'APPLY'},
        'base|b'     => \$options{'BASE_DIR'},
        'help|h'     => sub {pod2usage('-verbose' => 99, 'exitval' => 0)},
        'ignore|i=s@'  => \$options{'IGNORE'},
        'recurse|r'  => \$options{'RECURSE'},
        'verbose|v+' => \$options{'VERBOSE'},
    ) or die $log->fatal('Unable to process command line options') . "\n";

    Log::Any::Adapter->set(
        'Multiplex',
        'adapters' => {
            'Syslog' => ['options'   => 'pid,ndelay', 'log_level' => 'warning'],
            'Stderr' => ['log_level' => min(TRACE(), INFO() + $options{'VERBOSE'})],
        },
    );

    @ARGV
        or push(@ARGV, '.');

    my $basedir = path($options{'BASE_DIR'})->absolute;
    my @ignore  = ('@eaDir', $options{'IGNORE'}->@*);

    foreach my $folder (@ARGV) {
        path($folder)->visit(
            sub ($path, @) {
                none {$path =~ m/$_/} @ignore
                    or return;

                -l $path
                    or return;

                $path = $path->absolute;

                my $link_target = path(readlink $path);

                if ($link_target->is_relative) {
                    try {
                        my $link_realpath = $path->realpath;
                        if ($link_realpath =~ m/\A $basedir \/ /x) {
                            $log->tracef('Already good: %s -> %s', $path, $link_target);
                            return;
                        }
                    } catch ($err) {
                        chomp($err);
                        $log->warnf('Link is broken, skipping: %s -> %s', $path, $link_target);
                        return;
                    };
                } else {
                    if (!$link_target->exists) {
                        $log->warnf('Link is broken, skipping: %s -> %s', $path, $link_target);
                        return;
                    }
                    if ($link_target =~ m/\A $basedir \/ /x) {
                        my $link_parent = $path->parent;
                        $link_target = $link_target->relative($link_parent);
                        $log->infof('Fixing link: %s -> %s', $path, $link_target);

                        if ($options{APPLY}) {
                            $path->remove;
                            symlink $link_target, $path;
                        }

                        return;
                    }
                }

                $log->warnf('External symlink, skipping: %s -> %s', $path, $link_target);
            },
            {
                'follow_symlinks' => 0,
                'recurse'         => $options{'RECURSE'},
            },
        );
    }

    return 0;
}

exit main();

__END__
