#!/usr/bin/env perl

use v5.40;
use autodie;
use open ':locale';
use utf8;
use warnings     qw(FATAL utf8);
use experimental qw(class declared_refs defer refaliasing);

use Encode       qw(decode);
use Getopt::Long qw(:config auto_version bundling no_ignore_case);
use JSON::PP     qw();

use Web::Search qw(request_to_location_nt);

use constant {
    'JSON_ONE_LINE' => JSON::PP->new->canonical->utf8(0)->boolean_values(false, true)->pretty(false)->indent(0),
};

my %options = ('lang' => 'en');

sub main {
    GetOptions('lang|l=s' => \$options{'lang'},)
        or die "Unable to process command line options\n";

    my @queries = -t 0 ? @ARGV : do {
        binmode(STDIN, ':raw');
        <<>>;
    };

    foreach my $query (@queries) {
        my ($result, $body) = request_to_location_nt(decode('UTF-8', $query, Encode::FB_CROAK), $options{'lang'});
        say {*STDOUT} JSON_ONE_LINE()->encode($result);
        say {*STDERR} JSON_ONE_LINE()->encode($body);
    }

    return 0;
}

exit main();

__END__
