#!/usr/bin/env bash

# idea from https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

ROOT="$HOME/git"

SELECTED=$(
	fd -HuL -E 'bazel-*' -td -tf '\A.git\z' -d 4 "$ROOT" \
		| sed -E "s|^$ROOT/||; s|/.git/?$||"             \
		| fzf
)

if [[ -z $SELECTED ]]; then
	exit 0
fi

FULL_PATH="$ROOT/$SELECTED"
SELECTED_NAME=$(echo "$SELECTED" | tr . _)

if [[ -z "${TMUX:-}" && -z "$(pgrep tmux 2>/dev/null)" ]]; then
	tmux new-session -s "$SELECTED_NAME" -c "$FULL_PATH"
	exit 0
fi

if ! tmux has-session -t "$SELECTED_NAME" &>/dev/null; then
	tmux new-session -ds "$SELECTED_NAME" -c "$FULL_PATH"
fi

tmux switch-client -t "$SELECTED_NAME"
