#!/usr/bin/env bash

set -Eeuo pipefail

name="$(basename "$1")"
org="$(dirname "$1")"

function token-print() {
	local token="$1"
	local flag="$2"

	if [[ "$flag" == '--shell' ]]; then
		echo "$name=$token"
	else
		echo "$token"
	fi

	exit 0
}

if [[ -n "$org" ]] && token="$(pass show "org/$org" 2>/dev/null | grep -Pom 1 "$name=\K.*")"; then
	token-print "$token" "${2:-}"
elif token="$(pass show "token/$name" 2>/dev/null | head -1)"; then
	token-print "$token" "${2:-}"
elif [[ -r .env ]] && token="$(grep -F "$name=" < .env 2>/dev/null | sed "s|$name=||")"; then
	token-print "$token" "${2:-}"
fi

echo "token is not found: $1" >&2
exit 1
