#!/usr/bin/env perl

use v5.36;
use autodie;
use open ':locale';
use utf8;
use warnings     qw(FATAL utf8);
use experimental qw(builtin declared_refs defer for_list refaliasing try);

use POSIX      qw(EINVAL);
use List::Util qw(first);

sub main {
    my $result = EINVAL();

    if ($ENV{'DESKTOP_SESSION'} && $ENV{'DESKTOP_SESSION'} eq 'plasma') {
        $result = system(qw(
                qdbus org.kde.kglobalaccel /component/kcm_touchpad org.kde.kglobalaccel.Component.invokeShortcut
            ),
            'Toggle Touchpad',
        );
    } else {
        my $name   = _detect_name() // 'undefinded';
        my $output = `xinput list-props '$name'`;

        my ($enabled) = $output =~ m{Device\sEnabled .*:\s*(\d)}x;

        system(qw(xinput set-prop), $name, 'Device Enabled', !$enabled) == 0
            or die "Unable to toggle touchpad\n";

        $result = system(qw(notify-send -i dialog-positive), $name, !$enabled ? 'Is enabled' : 'Is disabled');
        $result == 0
            or die "Can't send desktop notification\n";
    }

    return $result;
}

sub _detect_name {
    state $names = ['DLL079F:01 044E:120B', 'SynPS/2 Synaptics TouchPad'];

    my $devices = `xinput`;
    return first {$devices =~ m/$_/} $names->@*;
}

exit main();

__END__
