#!/usr/bin/env -S perl -n

use v5.36;
use open ':locale';
use utf8;
use warnings     qw(FATAL utf8);
use experimental qw(builtin);

my $removed = chomp;
print builtin::trim($_), "\n" x $removed;

__END__
