#!/usr/bin/env bash

set -Eeuo pipefail

args="$(getopt --name="$0" --options 'p:' --longoptions 'paging:' -- "$@")"
eval set -- "$args"

paging='auto'

# shellcheck disable=SC2078,SC2034
while [ : ]; do
	case "$1" in
		-p | --paging) paging="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

cmd=(
	column --table --separator=$'\t' "$@"
)

if [[ "$paging" != 'never' ]] && [[ "$paging" == 'always' ]] || [[ -t 1 ]]; then
	LESS="${LESS:-"-x4 -iRSw --mouse"}"
	LESS+=' -F --header=1'
	"${cmd[@]}" | less
else
	exec "${cmd[@]}"
fi
