#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'cp' --longoptions 'paging:' -- "$@")
eval set -- "$args"

color='auto'
paging='auto'

while ((1)); do
	case "$1" in
		-c) color="always"; shift ;;
		-p) paging="always"; shift ;;
		--paging) paging="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

cmd=(
	column --table --separator=$'\t' --output-separator=$'\t' "$@"
)

if [[ "$paging" != 'never' ]] && [[ "$paging" == 'always' || -t 1 ]]; then
	LESS="${LESS:-"-x4 -iRSw --mouse"}"
	LESS+=' --header=1'
	[[ "$paging" == 'always' ]] || LESS+=' -F'
	"${cmd[@]}" | colored-tsv --color=always | less || true
elif [[ "$color" == "always" ]]; then
	"${cmd[@]}" | colored-tsv --color=always
else
	exec "${cmd[@]}"
fi
