#!/usr/bin/env bash

if [[ -t 0 && -r "$1" ]]; then
	name="${1%.*}"
	sqlite-utils insert --tsv "$name.db" "$name" "$1"
elif [[ ! -t 0 && -n "$1" ]]; then
	sqlite-utils insert --tsv "$1.db" "$1" -
else
	>/dev/stderr echo provide a file or STDIN and a table name
fi
