#!/usr/bin/env bash

set -Eeuo pipefail

VENDOR="${VENDOR:-0x090c}"
PRODUCT="${PRODUCT:-0x1000}"

args=(
	-audiodev "pa,id=snd0"
	-bios /usr/share/ovmf/x64/OVMF.4m.fd
	-cpu host
	-device ich9-intel-hda
	-device "hda-output,audiodev=snd0"
	-device "qemu-xhci,id=xhci"
	-device "usb-host,vendorid=$VENDOR,productid=$PRODUCT"
	-enable-kvm
	-k en-us
	-m 4G
	-nic "user,model=virtio-net-pci"
	# -boot menu=on
	-no-reboot
	-smp 2
	-vga virtio
)

exec qemu-system-x86_64 "${args[@]}"
