#!/usr/bin/env bash

set -Eeuo pipefail

if [[ -x "$(command -v nvim)" ]]; then
	exec nvim "$@"
elif [[ -x "$(command -v vim)" ]]; then
	exec vim "$@"
else
	COMMAND=$(PATH=${PATH//"$(dirname "$0")"/} command -v vi)
	exec "$COMMAND" "$@"
fi
