#!/usr/bin/env bash

set -Eeuo pipefail

args=$(getopt --name="$0" --options 'h:' --longoptions 'height:' -- "$@")
eval set -- "$args"

HEIGHT="${HEIGHT:-1440}"

while ((1)); do
	case "$1" in
		-h | --height) HEIGHT="$2"; shift 2 ;;
		--) shift; break ;;
	esac
done

# [[ "${#URL}" -lt 16 ]] && {
# 	URL="https://www.youtube.com/watch?v=$URL"
# }

yt_dlp_args=(
	--format="bv*[ext=webm][height<=${HEIGHT}]+ba/bv*[ext=mp4][height<=${HEIGHT}]+ba/b"
	--list-formats
	--no-simulate
	--prefer-free-formats
	# --write-info-json
	--write-thumbnail
)

umask 0002
exec yt-dlp "${yt_dlp_args[@]}" "$@"
