#!/usr/bin/env perl

use v5.36;
use autodie;
use open 'IO' => ':raw';
use utf8;
use warnings     qw(FATAL utf8);
use experimental qw(builtin declared_refs defer for_list refaliasing try);

use Encode       qw();
use Data::Dumper qw(Dumper);
use Getopt::Long qw(:config auto_version bundling no_ignore_case);
use JSON::PP     qw();

use YAML::XS qw();

use constant {
    'JSON'          => JSON::PP->new->pretty->space_before(0)->canonical->utf8(1),
    'JSON_ONE_LINE' => JSON::PP->new->pretty->space_before(0)->canonical->utf8(1)->indent(0),
};

my %options = (
    'JSON'    => 0,
    'LENIENT' => 0,
    'PERL'    => 0,
    'UNJSON'  => 0,
    'VERBOSE' => 0,
    'YAML'    => 0,
);

sub main() {
    GetOptions(
        'json|j'      => \$options{'JSON'},
        'lenient|l'   => \$options{'LENIENT'},
        'perl|p'      => \$options{'PERL'},
        'recursive|r' => \$options{'UNJSON'},
        'unjson|u'    => \$options{'UNJSON'},
        'verbose|v+'  => \$options{'VERBOSE'},
        'yaml|y'      => \$options{'YAML'},
    ) or die "Unable to process command line options\n";

    JSON()->relaxed if $options{'LENIENT'};

    my @formats = qw(JSON PERL YAML);
    if (1 < scalar grep {$options{$_}} @formats) {
        die sprintf "Please use only one format: %s\n", join ' | ', map lc, @formats;
    }

    my @data;
    my $type;

    local $YAML::XS::Boolean = 'JSON::PP'; ## no critic [Variables::ProhibitPackageVars]

    if (@ARGV) {
        foreach my $file (@ARGV) {
            -e -r $file
                or die "file does not exist: $file\n";
            open my $fh, '<', $file;
            process_file_handle(\@data, \$type, $fh);
            close $fh;
        }
    } else {
        process_file_handle(\@data, \$type, *STDIN);
    }

    if (@data) {
        print dump_data(\@data, $type);
    } else {
        warn "empty input\n";
    }

    return 0;
}

sub process_file_handle ($data_aref, $type_sref, $fh) {
    my \@data = $data_aref;
    my \$type = $type_sref;

    chomp(my @lines = <$fh>);

    return unless @lines;

    try {
        my @decoded = map {JSON()->decode($_)} @lines;
        $type ||= 'json';
        push @data, @decoded;
        return;
    } catch ($err) {
        ## not a multiline json
    };

    my $doc = join "\n", @lines;

    my $json_error;
    try {
        my $decoded = JSON()->decode($doc);
        $type ||= 'json';
        push @data, $decoded;
        return;
    } catch ($err) {
        ## not a json
        $json_error = $err;
    };

    my $yaml_error;
    try {
        my @decoded = YAML::XS::Load($doc);
        $type ||= 'yaml';
        push @data, @decoded;
        return;
    } catch ($err) {
        ## not a yaml
        $yaml_error = $err;
    };

    use Data::Printer;
    try {
        my $decoded = eval Encode::decode('UTF-8', $doc, Encode::FB_CROAK); ## no critic [BuiltinFunctions::ProhibitStringyEval]
        $type ||= 'perl';
        push @data, $decoded;
        return;
    } catch ($err) {
        ## not a perl
    };

    warn "unable to parse file as json: $json_error\n";
    die "unable to parse file as yaml: $yaml_error\n";
}

sub dump_data ($data_aref, $type) {
    my \@data = $data_aref;

    my $result;
    foreach my $it (@data) {
        unjson_recursive_inplace($it) if $options{'UNJSON'};
        if ($options{'PERL'}) {
            ## prevent hex codes for wide chars in output
            local *Data::Dumper::qquote = sub {
                my $str       = shift;
                my $new_lines = $str =~ s{(\R)}{\\n}g;
                if ($new_lines) {
                    $str =~ s{(["\$@])}{\\$1}g;
                    qq["$str"];

                } else {
                    $str =~ s{'}{\\'}g;
                    qq['$str'];
                }
            };
            local $Data::Dumper::Useperl = 1;

            # other option is to recode after dump
            # ->Dump =~ s/\\x [{] ([[:xdigit:]]{2,}) [}]/chr hex $1/gerx,

            $result .= Encode::encode(
                'UTF-8',
                Data::Dumper->new([$it])
                    ->Indent(1)
                    ->Quotekeys(1)
                    ->Sortkeys(1)
                    ->Terse(1)
                    ->Trailingcomma(1)
                    ->Useqq(0)
                    ->Dump,

                Encode::FB_CROAK,
            );
        } elsif ($options{'JSON'} || $type eq 'yaml') {
            if (@data > 1) {
                $result .= JSON_ONE_LINE()->encode($it) . "\n";
            } else {
                $result .= JSON()->encode($it);
            }
        } else {
            $result .= YAML::XS::Dump($it);
        }
    }

    return $result;
}

sub unjson_recursive_inplace ($data) {
    if (ref $data eq 'HASH') {
        $_ = __SUB__->($_) foreach values $data->%*;
    } elsif (ref $data eq 'ARRAY') {
        $_ = __SUB__->($_) foreach $data->@*;
    } elsif (!ref $data) {
        try {
            my $decoded = JSON()->decode($data);
            if (ref $decoded) {
                $data = $decoded;
                __SUB__->($data);
            }
        } catch ($e) {
            ## not an encoded json
        };
    }
    return $data;
}

exit main();

__END__
