#!/usr/bin/env -S perl -CALEO

use v5.36;

use YAML::XS         qw();
use Cpanel::JSON::XS qw();
use experimental     qw(builtin);

use constant {
    'JSON'          => Cpanel::JSON::XS->new->canonical->utf8(0)->unblessed_bool([1])->pretty->space_before(0),
    'JSON_ONE_LINE' => Cpanel::JSON::XS->new->canonical->utf8(0)->unblessed_bool([1])->pretty(0)->indent(0),
};

my @lines;
while (defined(my $line = <<>>)) {
    push @lines, $line;
}

my $input = join('', @lines);
my @data  = YAML::XS::Load($input);
if (-t 1 && @data == 1) {
    print JSON()->encode($data[0]);
} else {
    say JSON_ONE_LINE()->encode($_) foreach @data;
}

__END__
