#!/usr/bin/env perl

use v5.34;
use autodie;
use open 'IO' => ':raw';
use utf8;
use warnings;
use warnings 'FATAL' => qw(utf8);
use experimental qw(declared_refs refaliasing signatures try);

use JSON::PP ();
use Getopt::Long qw(:config auto_version bundling no_ignore_case);

use YAML::XS ();

use constant {
    'JSON'          => JSON::PP->new->pretty->space_before(0)->canonical->utf8(1),
    'JSON_ONE_LINE' => JSON::PP->new->pretty->space_before(0)->canonical->utf8(1)->indent(0),
};

my %options = (
    'LENIENT' => 0,
    'UNJSON'  => 0,
    'VERBOSE' => 0,
);

sub main() {
    GetOptions(
        'lenient|l'  => \$options{'LENIENT'},
        'unjson|u'   => \$options{'UNJSON'},
        'verbose|v+' => \$options{'VERBOSE'},
    ) or die "Unable to process command line options\n";

    JSON()->relaxed if $options{'LENIENT'};

    my @data;
    my $type;

    local $YAML::XS::Boolean = 'JSON::PP'; ## no critic [Variables::ProhibitPackageVars]

    if (@ARGV) {
        foreach my $file (@ARGV) {
            -e -r $file
                or die "file does not exist: $file\n";
            open my $fh, '<', $file;
            process_file_handle(\@data, \$type, $fh);
            close $fh;
        }
    } else {
        process_file_handle(\@data, \$type, *STDIN);
    }

    if (@data) {
        print dump_data(\@data, $type);
    } else {
        warn "empty input\n";
    }

    return 0;
}

sub process_file_handle ($data_aref, $type_sref, $fh) {
    my \@data = $data_aref;
    my \$type = $type_sref;

    chomp(my @lines = <$fh>);

    return unless @lines;

    try {
        my @decoded = map {JSON()->decode($_)} @lines;
        $type ||= 'json';
        push @data, @decoded;
        return;
    } catch ($err) {
        # not a multiline json input
    };

    my $doc = join "\n", @lines;

    my $json_error;
    try {
        my $decoded = JSON()->decode($doc);
        $type ||= 'json';
        push @data, $decoded;
        return;
    } catch ($err) {
        $json_error = $err;
    };

    my $yaml_error;
    try {
        my @decoded = YAML::XS::Load($doc);
        $type ||= 'yaml';
        push @data, @decoded;
        return;
    } catch ($err) {
        $yaml_error = $err;
    };

    warn "unable to parse file as json: $json_error\n";
    die "unable to parse file as yaml: $yaml_error\n";
}

sub dump_data ($data_aref, $type) {
    my \@data = $data_aref;

    my $result;
    foreach my $it (@data) {
        unjson_recursive_inplace($it) if $options{'UNJSON'};
        if ($type eq 'json') {
            $result .= YAML::XS::Dump($it);
        } else {
            if (@data > 1) {
                $result .= JSON_ONE_LINE()->encode($it) . "\n";
            } else {
                $result .= JSON()->encode($it);
            }
        }
    }

    return $result;
}

sub unjson_recursive_inplace ($data) {
    if (ref $data eq 'HASH') {
        $_ = __SUB__->($_) foreach values $data->%*;
    } elsif (ref $data eq 'ARRAY') {
        $_ = __SUB__->($_) foreach $data->@*;
    } elsif (!ref $data) {
        try {my $decoded = JSON()->decode($data); $data = $decoded if ref $decoded}
        catch ($e) { }
    }
    return $data;
}

exit main();

__END__
