[tools]
argc = "latest"
bat = "latest"
delta = "latest"
deno = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gemini-cli = "latest"
glow = "latest"
gum = "latest"
hurl = "latest"
hwatch = "latest"
jq = "latest"
just = "latest"
lazydocker = "latest"
lazyjournal = "latest"
neovim = "latest"
node = "lts"
oauth2c = "latest"
perl = "5.42.0"
ripgrep-all = "latest"
ruby = "latest"
step = "latest"
usage = "latest"
uv = "latest"
xh = "latest"
yq = "latest"
